### ISSUE TITLE
Issue with timezone running IBController in a headless chroot Ubuntu/Debian environment

### ISSUE THREAD

**Issue by grandtiger** [ib-controller/ib-controller#102]
Hi all, IBController is great, thanks for the good work! However, I am a new user and not a linux expert, and ran into a very weird issue with the timezone in a headless chroot environment. I tried it on both Ubuntu and Debian, and got the exact same result. This causes the IBController logging time stamp to be off by an hour, and what's worse, historical data downloaded from IB Gateway also off by an hour. I built a Ubuntu virtual machine and used it for data downloading as a short term solution, but the headless chroot environment is more lightweight. I have not yet tried docker container because I don't know much about it, but I suspect it might have similar issue.

I have verified that the timezone is set correctly. After some further research, I decided to use a simple Java program to test it. What I found is that if I just run the program as is, it will show timezone as "GMT-5", even though /etc/timezone is set to "America/New_York". However, adding the following vm options when running the test program seems to work around the issue and produced the correct output. 

```
-Duser.timezone="America/New_York"
```

Could anyone let me know where I can set the vm_options for IBController and IB Gateway? I believe tws.vmoptions is for TWS, does IB Gateway use it as well?

Thanks a lot in advance for your help!

**Comment by jaredbroad** [comment]
Did you solve this @grandtiger? You could try appending it to this variable in the start up script:
https://github.com/ib-controller/ib-controller/blob/master/resources/Scripts/IBController.sh#L212

You'll probably need to add your string to the end of the java_vm_options variable:
http://stackoverflow.com/questions/4181703/how-can-i-concatenate-string-variables-in-bash

**Comment by fyuval** [comment]
Here's how to implement what @jaredbroad  said.
Right after java_vm_options is initialized in IBController.sh (around line 310), add:

`#Force time zone to be New York

tz_var="-Duser.timezone=America/New_York"
java_vm_options=$java_vm_options$tz_var`
