### ISSUE TITLE
can't it support gateway 956?

### ISSUE THREAD

**Issue by viponedream** [ib-controller/ib-controller#103]
sorry to ask this question.
i install the ib gateway 956 ibgateway-latest-standalone-windows-x64
but when i click IBControllerGatewayStart.bat
it say this in the log
Error: TWS version 952 is not installed 

then i reinstall the 952, but  it say the version of the application you are running,  952.2k, is no longer supported.  and then it exit itself.

my ibcontroller is downloaded from here  : https://github.com/ib-controller/ib-controller/releases/tag/3.2.0

**Comment by rlktradewright** [comment]
Yes it works fine with Gateway 956.

It looks like you haven't you followerd the instructions and edited IBControllerGatewayStart.bat to include the correct version number.
