### ISSUE TITLE
API Client disconnecting automatically, if some market is closed

### ISSUE THREAD

**Issue by shakti-vyjayanthi** [ib-controller/ib-controller#106]
I am facing this problem of API client getting disconnected as soon as it connects, when some market is down. This happened when the Singapore market was down, the same is happening today when the HK market is down. If I have the gateway running, then the client connects, but if I start it programmatically, it does not connect. Is there something that I am not taking care of?

**Comment by rlktradewright** [comment]
The first thing to say is that API connections are nothing whatever to do with IBController. It has no involvement in them or knowledge of them.

 

The second thing is that API disconnects are usually a result of an unhandled exception occurring in your API client program. One way to deal with these is to use try…catch blocks in all your API callback functions and around every call to an API method: just print out the exception details and the stack trace in the catch blocks and exit the program to get basic information.

 

The third thing is that I don’t understand what you mean by ‘ If I have the gateway running, then the client connects, but if I start it programmatically, it does not connect’.  Please explain.

 

Richard

**Comment by shakti-vyjayanthi** [comment]
So, the first part is to connect to the IB by starting up the IB Gateway instance, which is connecting and happening successfully. The second part is the API Client connecting to the gateway instance. When I attempt to do the 2 part in the same execution of my code, it connects for a second, and then fails giving the warning HK market is dowm, and unsuported version error. 
But if I end this execution and just attempt the 2nd part (API Connection) it succeds. 
So is there something that I am supposed to take care of?

**Comment by rlktradewright** [comment]
Ok, I’m still not really understanding what you’re doing.

 

Are you saying that you run the IBController/Gateway startup and then connect to the API both from the same program? And your API connection drops here. 

 

And then you run the same program again but without it starting IBController/Gateway (because the Gateway is still running from before?), and it connects successfully?

 

If so I don’t really understand why you would want to start IBController/Gateway from your API program. What will you do when you write another API program? But that’s your choice. However I’d certainly advise you not to do this while you’re developing your API program: just start the gateway separately and leave it running. 

 

In any case, the ‘error’ callbacks that occur after an API connection is established are entirely normal and expected: they are simply informative messages, and are best ignored unless you have a particular reason to take action on them .

**Comment by shakti-vyjayanthi** [comment]
What you have understood is correct. I do have a use case where I have to start the IBGateway every time before connecting the API. The problem is that if the messages are causing hindrance in our application as the API client is disconnected right after connecting, we are unable to proceed further, to get the rest of the information

**Comment by rlktradewright** [comment]
Ok, I'm sure you have good reasons for your use case.

But none of what you've said gives me any reason to think that this is anything to do with IBController. All IBController does is load TWS or Gateway into the IBController process and handle the various dialogs that pop up (eg login). As I said before API connections are nothing whatever to do with IBController.

However I'm always willing to help where I can, but you could help a bit by providing full information about what you're experiencing.

For example:

* are you starting IBController by shelling out to the scripts, or are you loading it directly into your program's process?

* having loaded IBController, how do you decide when it's ready to accept API connections? Do you just wait a fixed time, or do you keep repeating the connection attempt until it succeeds? Note that in older versions of TWS there was a problem where connecting too quickly after TWS started didn't work correctly, but this has long been fixed. However it's possible that something similar is happening here.

* which version of TWS are you using?

* what are the exact error messages that you're receiving?

* it's still not clear to me whether your program is actually terminating as a result of an exception. You said that '_it connects for a second, and then fails giving the warning HK market is dowm, and unsuported version error_'. By 'fail' do you mean it actually crashes or just that it doesn't do what you expected? If it crashed, then why aren't you catching the exception to determine what its cause is?
