### ISSUE TITLE
Transfer session

### ISSUE THREAD

**Issue by georgiosd** [ib-controller/ib-controller#108]
Hi!

Any chance you can add a setting to deal with the "someone has logged in with this username from another location" scenario?

IB's "great" monster doesn't let you log in from two locations so I'd like to be able to login from my phone to check my portfolio at times that I know the TWS API will not be sending orders.

I would imagine it would click the button after some timeout.

Let me know what you think!

Thanks
Georgios

**Comment by benalexau** [comment]
One option is a second username on your account. Full info at http://ibkb.interactivebrokers.com/node/1004.

**Comment by georgiosd** [comment]
You rock! Had no idea! Thanks!
