### ISSUE TITLE
A Docker Image for IBController?

### ISSUE THREAD

**Issue by buzzcloudau** [ib-controller/ib-controller#109]
I have had no luck getting this to work in a docker instance. 
- I cant get it to run in "paper" mode. 
- I can not connect to the instance externally.

Is there any chance of an official Docker image?

**Comment by buzzcloudau** [comment]
This is my fork of another project. Apart from updating the java version, none of my changes have helped.

https://github.com/buzzcloudau/docker-ibcontroller

I think I have have made things worse by playing with the ports. Any help in getting this running would be appreciated.

**Comment by benalexau** [comment]
I doubt Docker images are a priority for this project, although @jaredbroad might chime in with a different view.

Instead I would suggest a couple of resources that you might find helpful in configuring IB Controller via a virtual framebuffer:

1. [How to setup IBController on a headless Ubuntu](https://docs.google.com/document/d/1qWt43XamkNt6-P9QyyiyT0kJLBQa7g23atF_Ti5rEVg/edit) is a highly detailed and up-to-date (June 2016) discussion of a similar configuration.
2. [ib-controller AUR package](https://aur.archlinux.org/packages/ib-controller/) is my Arch package, which contains a [systemd unit file](https://aur.archlinux.org/cgit/aur.git/tree/ibcontroller@.service?h=ib-controller) that uses `xvfb`. I can confirm this configuration definitely works, as I use it in production.
3. [Dmitry's TWS API FAQ](http://goo.gl/TRkeRK) offers the most detailed, curated community collection of TWS API (and some IBController-related) help.

Hopefully one of the above will assist.

**Comment by buzzcloudau** [comment]
Thanks.

It looks like the project I started with is uisng your AUR package, but is calling the jar files directly and not using your AUR package, but invoking IB Controller differently.

I will take a look at that file and see if I can make the switch to it.

**Comment by benalexau** [comment]
> the project I started with is using your AUR package

Haha,  so it does.

IB have been frequently changing the installer details and JAR names since March 2016. The other AUR package installed by that Docker build is `ib-tws`, and its [change log](https://aur.archlinux.org/cgit/aur.git/log/?h=ib-tws) reports at least three breaking JAR layout changes in that brief time. 

Can you post the log and/or error messages you're seeing, and the final contents of `/etc/ibcontroller/conf.ini` once IB Controller tries to launch? Can you also confirm that the specified paths exist (eg `/var/run/ibcontroller/tws/conf` and `/var/run/xvfb/`) and the process has RW access to them? Does it work if you a known-to-exist, RW-enabled path like `/tmp`?

**Comment by buzzcloudau** [comment]
I have attached two sets of (hopefully sanitised) files.

The docker instance was invoked with

```
docker run -d --env IB_IbLoginId={username} --env IB_IbPassword={password} --env IB_TradingMode=paper ibc;
```

That produced the attached ibgateway.log and the jts.ini files.

Notice this response

```
Connection to server failed: <html>You have selected the Live Trading Mode, but the specified user <br> is a Paper Trading user. <br><br>Please select the correct Trading Mode
```

While the inside the running docker instance, I restarted the controller with the same script.

```
/usr/sbin/xvfb-run \
    --auto-servernum \
    -f \
    /var/run/xvfb/ \
    java \
    -cp \
    /usr/share/java/ib-tws/*:/usr/share/java/ibcontroller/* \
    -Dsun.java2d.noddraw=true \
    -Dswing.boldMetal=false \
    -Dsun.locale.formatasdefault=true -Xmx512M \
    ibcontroller.IBGatewayController \
    /etc/ibcontroller/conf.ini;
```

It picked up the environment variables, and correctly detected the paper trading mode (see the output from ibtageway_2.log.txt and the jts.ini file was correctly updated to trading mode 'p' (jts_2.ini.txt) - I wasn't expecting this one to run, as there already was an instance running, but it does show that the script did switch to paper on the second instance.



[ibgateway_2.log.txt](https://github.com/ib-controller/ib-controller/files/429185/ibgateway_2.log.txt)
[ibgateway.log.txt](https://github.com/ib-controller/ib-controller/files/429182/ibgateway.log.txt)
[jts_2.ini.txt](https://github.com/ib-controller/ib-controller/files/429183/jts_2.ini.txt)
[jts.ini.txt](https://github.com/ib-controller/ib-controller/files/429184/jts.ini.txt)

**Comment by buzzcloudau** [comment]
To answer your question re folders existing, here is the output for both

```
drwxr-xr-x 2 root root 4096 Aug 22 00:32 /var/run/xvfb/
drwxr-xr-x 4 root root 4096 Aug 22 00:33 /var/run/ibcontroller/tws/conf
```

**Comment by buzzcloudau** [comment]
I have managed to get the paper trading account logging in.

I moved the ``/var/run/ibcontroller/tws/conf`` folder creation from the Docker file to ``start.sh`` and also modified ``start.sh`` to match your ``ibcontroller@.service``

I just need to work on getting the port settings right.

**Comment by jaredbroad** [comment]
We're actually designing a docker image for this now @buzzcloudau. It should be up and shared in a week or so. We might go with Vagrant instead just because it'll be much easier and more isolated.

**Comment by benalexau** [comment]
@buzzcloudau I noticed from the email notifications you appeared to get it working when you moved the directory creation. Does this mean https://github.com/buzzcloudau/docker-ibcontroller now contains a working configuration? 

Just on your folder paths, I'd suggest `/var/run/xvfb/` have a suffix that denotes the instance or at least be renamed to reflect IBController so as to avoid confusion with other `xvfb`-based processes running on the box. Also the permissions shown would require root access to write to the folders. Do you run this process as root (I wouldn't recommend this, as TWS doesn't require root permission)?

**Comment by buzzcloudau** [comment]
Sorry, no. Its not working.

I deleted my comment because the changes I made were actually just making it bypass my environment arguments and loading straight to the edemo account.

I have been running this as root. Until I get it up and running, I didn't want to have another issue to work around (user permissions).

**Comment by benalexau** [comment]
I just updated the AUR to add new properties introduced by IBController. I don't think it will fix your issue, but might be worth another try. I have locally been able to use the AUR with a variety of advisor paper, advisor production, trust production, trust paper accounts, edemo and fdemo users. As such I'm fairly confident in the AUR.

Have you tried verifying your username, password and `TradingMode=` settings in a manually-installed (non-AUR, non-Docker) IBController on your main operating system?

**Comment by buzzcloudau** [comment]
Thanks @benalexau - Still no luck. I will keep trying. I have the paper account working fine using the non-docker setup from your first link provided above. (headless Ubuntu)

I have have to, I can keep going with that one. But I will keep trying with the Docker image.

**Comment by jaredbroad** [comment]
We shared our headless ubuntu start up script here. Its used in the open source platform QuantConnect/LEAN: https://github.com/QuantConnect/Lean/blob/master/Brokerages/InteractiveBrokers/run-ib-controller.sh

To make this work with docker you'll need to install all the dependencies in the build file and then possibly tidy any orphan processes on leaving the docker container.

**Comment by ryankennedyio** [comment]
@jaredbroad I'm working on this:

https://github.com/ryankennedyio/ib-docker

Seems OK -- I believe Docker is definitely the way to go instead of Vagrant, what's the thought behind Vagrant as the way to go? With Docker, we have a properly isolated environment and can inject anything we need (configuration, parameters, settings, etc) into the container at runtime.

That aside, only thing currently not working with my link is actually exposing the port to the host... Fairly important! I think it might be to do with the port not being allocated as part of the shell script that 'launches' the IB program. Anyway, working on that. Also need to get the log file displaying to stdout.

**Comment by moconnell** [comment]
Hello all. I am also attempting to get this to work on Docker and have cloned @buzzcloudau 's repo https://github.com/buzzcloudau/docker-ibcontroller locally.

It seems like it's almost there; if I spin up the image locally, it looks like it starts ok - but I am unable to connect using swigibpy on either 4001 or 4003:

```$ docker run -p 4001-4003:4001-4003 --rm --name ib docker-ibcontroller
22:53:05:945 IBController: Properties file /root/IBController/IBController.ini not found
System Properties
------------------------------------------------------------
java.runtime.name = OpenJDK Runtime Environment
sun.boot.library.path = /usr/lib/jvm/java-8-openjdk/jre/lib/amd64
java.vm.version = 25.102-b14
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = OpenJDK 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /
java.runtime.version = 1.8.0_102-b14
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /usr/lib/jvm/java-8-openjdk/jre/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = ANSI_X3.4-1968
java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 4.4.20-moby
user.home = /root
user.timezone = UTC
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = ANSI_X3.4-1968
java.specification.version = 1.8
java.class.path = /usr/share/java/ib-tws/locales.jar:/usr/share/java/ib-tws/total-2015c.jar:/usr/share/java/ib-tws/twslaunch-958.jar:/usr/share/java/ib-tws/log4j-api-2.5.jar:/usr/share/java/ib-tws/twslaunch-install4j-1.7.jar:/usr/share/java/ib-tws/jts4launch-958.jar:/usr/share/java/ib-tws/log4j-core-2.5.jar:/usr/share/java/ibcontroller/ibcontroller.jar
user.name = root
java.vm.specification.version = 1.8
sun.java.command = ibcontroller.IBGatewayController /etc/ibcontroller/conf.ini
java.home = /usr/lib/jvm/java-8-openjdk/jre
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.8.0_102
java.ext.dirs = /usr/lib/jvm/java-8-openjdk/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /usr/lib/jvm/java-8-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk/jre/classes
java.vendor = Oracle Corporation
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.cpu.isalist = 
------------------------------------------------------------
22:53:05:956 IBController: using default settings provider: ini file is /etc/ibcontroller/conf.ini
22:53:05:957 IBController: using default login manager: getting username and password from args but not found. Will get from settings
22:53:05:957 IBController: using default config dialog manager: constructor parameter isGateway=true
22:53:05:957 IBController: using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
22:53:05:959 IBController: using default config dialog manager
22:53:05:968 IBController: IBControllerServer is started.
22:53:06:064 IBController: IBControllerServer listening on address: 127.0.0.1 port: 7464
22:53:06:191 IBController: TWS settings directory is /var/run/ibcontroller/tws/conf
22:53:07:155 IBController: Getting config dialog
22:53:07:155 IBController: Creating config dialog future
22:53:08:751 IBController: detected frame entitled: IB Gateway; event=Activated
22:53:08:759 IBController: detected frame entitled: IB Gateway; event=Opened
22:53:08:888 IBController: Click button: Login
22:53:09:307 IBController: detected frame entitled: IB Gateway.  API Account: edemo; event=Activated
22:53:09:309 IBController: detected frame entitled: IB Gateway.  API Account: edemo; event=Opened
22:53:09:310 IBController: Found Gateway main window
22:53:09:832 IBController: detected frame entitled: Authenticating...; event=Activated
22:53:09:834 IBController: detected frame entitled: Authenticating...; event=Opened
LogModuleConfigurator-Init: Log4j Ver2.x found on classpath
LogModuleConfigurator-Init: LogModuleConfigurator initialized with Log4j Verd.x
22:53:15:141 IBController: detected frame entitled: Starting application...; event=Closed
22:53:15:559 IBController: detected dialog entitled: DU15002 Trader Workstation Configuration (Demo System); event=Activated
22:53:15:567 IBController: detected dialog entitled: DU15002 Trader Workstation Configuration (Demo System); event=Opened
22:53:15:585 IBController: Performing port configuration
22:53:15:759 IBController: TWS API socket port was set to 4002
22:53:15:760 IBController: TWS API socket port now set to 4001
22:53:15:760 IBController: Click button: OK
22:53:15:853 IBController: detected dialog entitled: DU15002 Trader Workstation Configuration (Demo System); event=Closed
```

My app log (N.B. I tried 4003 as well...):

```
2016-09-30 12:57:13,341 - Gateway#888 - INFO - Connecting to localhost:4001
2016-09-30 12:57:13,342 - Gateway#888 - WARNING - (-1, 502, 'Couldn\'t connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.')
2016-09-30 12:57:18,343 - Gateway#888 - WARNING - Waiting for order ID to be set: attempt #2
2016-09-30 12:57:18,345 - Gateway#888 - WARNING - (-1, 502, 'Couldn\'t connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.')
2016-09-30 12:57:23,346 - Gateway#888 - WARNING - Waiting for order ID to be set: attempt #3
2016-09-30 12:57:23,346 - Gateway#888 - WARNING - (-1, 502, 'Couldn\'t connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.')
2016-09-30 12:57:28,346 - Gateway#888 - WARNING - Waiting for order ID to be set: attempt #4
2016-09-30 12:57:28,347 - Gateway#888 - WARNING - (-1, 502, 'Couldn\'t connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.')
2016-09-30 12:57:33,348 - Gateway#888 - WARNING - Waiting for order ID to be set: attempt #5
2016-09-30 12:57:33,348 - Gateway#888 - WARNING - (-1, 502, 'Couldn\'t connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.')

```

I get the same if I spin it up with `docker-compose`. Interestingly, if I set environment variables for user & password, it appears to stop before `Performing port configuration`.

Anyone got any clues?

**Comment by ryankennedyio** [comment]
@jaredbroad  @moconnell finally found time yesterday to grind through this. I have it working now at https://github.com/ryankennedyio/ib-docker

I believe the issues everyone is having is that within docker, the IB process is listening on `:::4001`.  4001 is then mounted from host into docker, but no connections can be made. This is because the process within docker must be available at `0.0.0.0:4001`.

I'll probably do a bit of a tidy up and a blog post about it in a couple of days, once I remove the dependancy on hardcoding `4003`.

**Comment by henryshtang** [comment]
I've also tried to get a ib docker image but I've found it's not very flexible in most available choices and so I've decided to do it on my own. And it ship my trading engine in the docker image too so I can just deploy it to cloud and running everything I need. Sometimes you can't really have everything provided by others and do the work yourself.

**Comment by grandtiger** [comment]
Hi Henry,

Is there any way for me to get your docker image? I'd love to try your solution.

Thanks,
George

**Comment by henryshtang** [comment]
My docker image included not just the IB Controller and it's headless dependencies, but also include my proprietary trading engine which isn't offered to public. So I'm not going to publish it. But if you have any specific questions on creating the docker image yourself. I can help answering.  

The "How to setup IBController on a headless Ubuntu" Doc mentioned above is a good starting point.

**Comment by grandtiger** [comment]
Thanks, Henry! Perfectly understood. 

Is it possible to just share the portion of your Dockerfile that handles IB Controller and it's headless dependencies? That's all I need. Thanks again!

**Comment by ryankennedyio** [comment]
@grandtiger I have a [repo available](https://github.com/ryankennedyio/ib-docker) that does this & can confirm it works. Happy for it to be forked & full credit to the ib-controller team for doing the entirety of the hard work.

Have a blog post [here](http://ryankennedy.io/interactive-brokers-api-docker/) for a little more detail.

**Comment by grandtiger** [comment]
Thanks a lot, Ryan! I have been busy at work, and had some issues with my home server lately. I'll try this out during the holiday. Have a happy thanksgiving!

Thanks,
George

**Comment by rlktradewright** [comment]
Given the interest in containerisation, I think it would be helpful if the results of this thread could be succinctly summarised (preferably as a new Issue) giving links to repositories offering tested container images (ie not early stage 'works in progress').

Please avoid the use of the word 'official': that implies endorsement by the IBController team.

**Comment by josefstr** [comment]
I've also spend some time on the weekend getting ib-controller and docker work. here is the result:
you can run multiple instances (multiple gateways).
https://github.com/josefstr/docker.ib-controller

**Comment by moconnell** [comment]
@ryankennedyio 's container works like a charm for me. Thanks 👍
