### ISSUE TITLE
Small mistake in UserGuide.pdf

### ISSUE THREAD

**Issue by GitChub** [ib-controller/ib-controller#11]
There seems to be a mistake in the UserGuide.pdf (or, alternately, the behavior of IBController with respect to the default value of the IbDir setting is incorrect on the Windows platform): 

For the "IbDir" setting in the IBController.ini file, UserGuide.pdf says "You will need to set this if you are using Unix". However, that's misleading because even if you are using Windows, it seems you still need to set it. I ran into an error about not being able to find "jts.ini".  After I set IbDir to "C:\\\\Jts" the error went away.  (Note that IbDir was set to nothing in the original IBController.ini file.) Other than that, everything in the UserGuide.pdf seemed to work for me.

From my reading, the UserGuide.pdf seems to imply that as long as the standalone TWS (Trader WorkStation) software is installed in C:\Jts, then you don't need to set IbDir.  However, by default, the IbDir setting in IBController.ini is blank, which seems to translate to the root directory "\" on Windows, which would probably never be a good place to install the standalone TWS software.

I and at least one other person I know encountered this problem, so I thought it best to report the issue as others are likely to encounter it as well.

Thanks for making this great solution available!

**Comment by benalexau** [comment]
Closing ticket as the conversation (and fix) has moved to pull request #17.
