### ISSUE TITLE
Problems Installing IBContoller

### ISSUE THREAD

**Issue by algo94** [ib-controller/ib-controller#110]
Looks like a very useful program.

I have downloaded the ZIP. 
Extracted to my desktop under a folder called IBController
Path looks like C:\Users\fred_000\Downloads\IBController-3.2.0

When I run the .bat file it cannot find the path

Looked at the .ini file for a path designation and none found.

Should I just edit my environment variables to add the path above?

Thanks

**Comment by rlktradewright** [comment]
RTFM.

In particular the section in the User Guide entitled **Installing IBController**.

You'll find everything is much easier if you stick to the defaults, ie put IBController into C:\IBController rather than a folder on the Desktop.

If you really want it in the folder you're currently using, you'll need to edit the IBControllerStart.bat file. The comments in the file will help you.

**Comment by algo94** [comment]
I have been running IBController for several days 24 hours a day using version 958 without issue.  I tried to install an earlier version of the TWS as I noticed that there were some bugs after version 954, but unfortunately when I installed and ran 952 from IB's site and tried to connected.  IB flashed a message that 952 was no longer supported.

The issue occurred when a message generated by TWS appeared and IBController did not handle the message.  TWS was asking whether I wanted to login after a loss in connectivity in the middle of the night.  Any solutions by either a parameter setting or other fix.  Thanks.

The logs file is as follows: (as small snippet)

21:00:21:218 IBController: detected window: type=javax.swing.JWindow; event=Opened
21:00:34:282 IBController: detected frame entitled: DU480052 Interactive Brokers (Simulated Trading); event=Activated
21:00:34:610 IBController: detected window: type=javax.swing.JWindow; event=Closed
21:00:34:612 IBController: detected window: type=javax.swing.SwingUtilities$SharedOwnerFrame; event=Closed
21:45:05:513 IBController: detected frame entitled: DU480052 Interactive Brokers (Simulated Trading); event=Activated
00:22:49:995 IBController: detected frame entitled: Connecting to server...; event=Activated
00:22:49:999 IBController: detected frame entitled: Connecting to server...; event=Opened
00:26:46:870 IBController: detected dialog entitled: Re-login is required; event=Activated
00:26:46:871 IBController: detected dialog entitled: Re-login is required; event=Opened
00:26:46:871 IBController: Let user choose whether to re-login
00:29:50:436 IBController: detected frame entitled: Attempt 10: connecting to server...; event=Activated
00:29:50:436 IBController: detected dialog entitled: Re-login is required; event=Closed
00:29:50:647 IBController: detected dialog entitled: Re-login is required; event=Activated
00:29:50:647 IBController: detected dialog entitled: Re-login is required; event=Opened
00:29:50:647 IBController: Let user choose whether to re-login

**Comment by rlktradewright** [comment]
The first thing to say is that I just downloaded and installed TWS 952.2r (the latest 952 release) and I didn't get any messages about it no longer being supported. In fact it is still the 'stable' version. (Then I installed the self-updating version, and when I ran that something did flash up but it was much too quick to read: but in any case, the self-updating version is an irrelevance if you want to use IBController, which can only use the standalone versions.)

The log extract you included seems to indicate that another instance of TWS tried to login to the same user, and chose to continue with their logon when informed that there was already an existing session, If you were logged in to the demo account, then this is just something that happens now and again (and is one reason for not using the demo account, which is really more trouble than it's worth: a free trial account is much, much better). I really wouldn't recommend running TWS with the demo account continuously for several days.

If you were logged in to a real account, and you accidentally started another instance, you can protect yourself by setting ExistingSessionDetectedAction=primary for your main login: if another session is started, and that user chooses to continue with the login, the original session will then relogin and the other user's login will be rejected.

I would suggest that you don't use ExistingSessionDetectedAction=primary with the demo account, as at some point you'll probably just annoy another user who tries to log on and gets thrown off.

**Comment by ashpriom** [comment]
@rlktradewright Hi Richard,
I am concerned that I was logged out.

I didn't attempt to login anywhere else.
I am using a trial account.
I have `ExistingSessionDetectedAction` set to manual.

Looked at this file https://github.com/ib-controller/ib-controller/blob/master/src/ibcontroller/ReloginDialogHandler.java but no clue why I was logged out.

00:47:15:351 IBController: detected frame entitled: Login; event=Opened
00:47:15:560 IBController: detected frame entitled: Attempt 2: server error, will retry in 1 seconds...; event=Activated
00:48:07:153 IBController: detected dialog entitled: Re-login is required; event=Opened
00:48:07:157 IBController: Let user choose whether to re-login
00:48:07:179 IBController: detected dialog entitled: Re-login is required; event=Activated
00:51:11:487 IBController: detected dialog entitled: Re-login is required; event=Closed
00:51:11:544 IBController: detected frame entitled: Attempt 7: Authenticating...; event=Activated
00:51:11:630 IBController: detected dialog entitled: Re-login is required; event=Opened
00:51:11:630 IBController: Let user choose whether to re-login
00:51:12:565 IBController: detected dialog entitled: Re-login is required; event=Activated
00:54:16:454 IBController: detected dialog entitled: Re-login is required; event=Closed
00:54:16:522 IBController: detected frame entitled: Attempt 8: Authenticating...; event=Activated
00:54:16:592 IBController: detected dialog entitled: Re-login is required; event=Opened
00:54:16:593 IBController: Let user choose whether to re-login
00:54:17:558 IBController: detected dialog entitled: Re-login is required; event=Activated
00:57:21:491 IBController: detected dialog entitled: Re-login is required; event=Closed
00:57:21:550 IBController: detected frame entitled: Attempt 9: Authenticating...; event=Activated
00:57:21:613 IBController: detected dialog entitled: Re-login is required; event=Opened
00:57:21:613 IBController: Let user choose whether to re-login
00:57:22:557 IBController: detected dialog entitled: Re-login is required; event=Activated
01:00:26:602 IBController: detected dialog entitled: Re-login is required; event=Closed
01:00:26:698 IBController: detected frame entitled: Attempt 10: Authenticating...; event=Activated
01:00:26:699 IBController: detected dialog entitled: Re-login is required; event=Opened
01:00:26:699 IBController: Let user choose whether to re-login
01:00:27:557 IBController: detected dialog entitled: Re-login is required; event=Activated
01:03:31:641 IBController: detected dialog entitled: Re-login is required; event=Closed
01:03:31:687 IBController: detected frame entitled: Attempt 11: Authenticating...; event=Activated
01:03:31:747 IBController: detected dialog entitled: Re-login is required; event=Opened
01:03:31:747 IBController: Let user choose whether to re-login
01:03:32:558 IBController: detected dialog entitled: Re-login is required; event=Activated
01:06:36:683 IBController: detected dialog entitled: Re-login is required; event=Closed
01:06:36:725 IBController: detected frame entitled: Attempt 12: Authenticating...; event=Activated
01:06:36:777 IBController: detected dialog entitled: Re-login is required; event=Opened
01:06:36:781 IBController: Let user choose whether to re-login
01:06:37:558 IBController: detected dialog entitled: Re-login is required; event=Activated
01:09:41:662 IBController: detected dialog entitled: Re-login is required; event=Closed
01:09:41:705 IBController: detected frame entitled: Attempt 13: Authenticating...; event=Activated
01:09:41:757 IBController: detected dialog entitled: Re-login is required; event=Opened
01:09:41:757 IBController: Let user choose whether to re-login
01:09:42:556 IBController: detected dialog entitled: Re-login is required; event=Activated
01:12:46:768 IBController: detected dialog entitled: Re-login is required; event=Closed
01:12:46:806 IBController: detected frame entitled: Attempt 14: Authenticating...; event=Activated
01:12:46:854 IBController: detected dialog entitled: Re-login is required; event=Opened
01:12:46:855 IBController: Let user choose whether to re-login
01:12:47:556 IBController: detected dialog entitled: Re-login is required; event=Activated
01:15:51:710 IBController: detected dialog entitled: Re-login is required; event=Closed
01:15:51:733 IBController: detected frame entitled: Attempt 15: Authenticating...; event=Activated
01:15:51:786 IBController: detected dialog entitled: Re-login is required; event=Opened
01:15:51:786 IBController: Let user choose whether to re-login
01:15:52:558 IBController: detected dialog entitled: Re-login is required; event=Activated
01:18:56:747 IBController: detected dialog entitled: Re-login is required; event=Closed
01:18:56:795 IBController: detected frame entitled: Attempt 16: Authenticating...; event=Activated
01:18:56:841 IBController: detected dialog entitled: Re-login is required; event=Opened
01:18:56:841 IBController: Let user choose whether to re-login
01:18:57:557 IBController: detected dialog entitled: Re-login is required; event=Activated
01:22:01:798 IBController: detected dialog entitled: Re-login is required; event=Closed
01:22:01:820 IBController: detected frame entitled: Attempt 17: Authenticating...; event=Activated
01:22:01:897 IBController: detected dialog entitled: Re-login is required; event=Opened
01:22:01:897 IBController: Let user choose whether to re-login
01:22:02:556 IBController: detected dialog entitled: Re-login is required; event=Activated
01:25:06:836 IBController: detected dialog entitled: Re-login is required; event=Closed
01:25:06:868 IBController: detected frame entitled: Attempt 18: Authenticating...; event=Activated
01:25:06:942 IBController: detected dialog entitled: Re-login is required; event=Opened
01:25:06:942 IBController: Let user choose whether to re-login
01:25:07:557 IBController: detected dialog entitled: Re-login is required; event=Activated
01:28:11:825 IBController: detected dialog entitled: Re-login is required; event=Closed
01:28:11:880 IBController: detected frame entitled: Attempt 19: Authenticating...; event=Activated
01:28:11:946 IBController: detected dialog entitled: Re-login is required; event=Opened
01:28:11:946 IBController: Let user choose whether to re-login
01:28:12:558 IBController: detected dialog entitled: Re-login is required; event=Activated
01:31:16:914 IBController: detected dialog entitled: Re-login is required; event=Closed
01:31:16:937 IBController: detected frame entitled: Attempt 20: Authenticating...; event=Activated
01:31:16:985 IBController: detected dialog entitled: Re-login is required; event=Opened
01:31:16:985 IBController: Let user choose whether to re-login
01:31:17:558 IBController: detected dialog entitled: Re-login is required; event=Activated
01:34:21:956 IBController: detected dialog entitled: Re-login is required; event=Closed
01:34:21:997 IBController: detected frame entitled: Attempt 21: Authenticating...; event=Activated
01:34:22:061 IBController: detected dialog entitled: Re-login is required; event=Opened
01:34:22:062 IBController: Let user choose whether to re-login
01:34:22:559 IBController: detected dialog entitled: Re-login is required; event=Activated
01:37:26:987 IBController: detected dialog entitled: Re-login is required; event=Closed
01:37:27:028 IBController: detected frame entitled: Attempt 22: Authenticating...; event=Activated
01:37:27:079 IBController: detected dialog entitled: Re-login is required; event=Opened
01:37:27:079 IBController: Let user choose whether to re-login
01:37:28:556 IBController: detected dialog entitled: Re-login is required; event=Activated
01:40:32:027 IBController: detected dialog entitled: Re-login is required; event=Closed
01:40:32:082 IBController: detected frame entitled: Attempt 23: Authenticating...; event=Activated
01:40:32:121 IBController: detected dialog entitled: Re-login is required; event=Opened
....
more than 600 attempts with similar messages.

Looking forward to suggestions.
