### ISSUE TITLE
Client is not authorized to connect to ServerException in thread "main" java.awt.AW\ TError: Can't connect to X11 window server using ':10' as the value of the DISPLAY \ variable.

### ISSUE THREAD

**Issue by the-entp** [ib-controller/ib-controller#113]
Hey so I'm starting IBController and I see this:
Client is not authorized to connect to ServerException
 in the log files. The display variable is correct, but I'm wondering why IBController is not able to access the vncserver I see up.

I run sudo -s $(DISPLAY=:10 /home/ubuntu/IBController/IBControllerStart.sh) via cronjob and get this error.

If I just run that line on the command line, IBController runs perfectly.

Is there a specific reason IBController doesn't work as well when launched via cronjob?
Can someone help?

**Comment by rlktradewright** [comment]
@the-entp Are you still having a problem here? If not, please close this issue.
