### ISSUE TITLE
Problem with use of 'tr' in Scripts/DisplayBannerAndLaunch.sh

### ISSUE THREAD

**Issue by cactus74** [ib-controller/ib-controller#117]
The use of tr [:lower:] [:upper:] can be problematic depending on LOCALES. It throws the following error:
tr: misaligned [:upper:] and/or [:lower:] construct

This is because in certain LOCALES the number of lower and upper case characters is different.

I would suggest the use of tr '[a-z]' '[A-Z]'.

**Comment by rlktradewright** [comment]
It looks like the problem you're referring to has long ago been fixed:

http://gnu-coreutils.7620.n7.nabble.com/tr-upper-lower-misaligned-construct-td10011.html

However there is a potential problem here in that there should be quotes around the [:lower:] and [:upper:] to prevent them being treated as regular expressions by the shell's filename expansion. So I'll fix that.
