### ISSUE TITLE
Support for downgrading/upgrading Java versions

### ISSUE THREAD

**Issue by bhanuc** [ib-controller/ib-controller#119]
I am facing an issue with requesting realtimebar using IB-Controller where the response is erratic, where I am getting response only sometime(I managed to get it just once). 
It is documented issue, also discussed here - https://www.interactivebrokers.com/fluxbb/viewtopic.php?id=52552 , where people who downgraded to Java 1.5 did not face the issue. The issue is very old and might be fixed in recent versions but I just wish to test my hypothesis.
It is also mentioned that java 1.5 was the official supported version.
I wish to know if such a downgrade is feasible or can be supported. If not supported, kindly give me some head-ups on doing so. 
I can give a procedure to replicate the issue too but it is evident from the thread that the particular may arise if different java version is chosen. I just wish to test using multiple java versions.

**Comment by benalexau** [comment]
The linked thread is from 2008.

Modern IB TWS class files all use internal version 52, meaning Java 8 or above is required to even run them. I don't know the solution to your issue, but you will need Java 8 or above to even try out fixes. I'd suggest contacting IB TWS support and see what they say.

I'm unclear how this is an IB Controller issue in the first place. Does the problem only occur when using via IB Controller or does it occur with vanilla TWS as well?

**Comment by bhanuc** [comment]
After debugging around with socat and working with vanilla TWS, it seems the issue is either with library which I am using or IB TWS. I will get in touch with support and update here accordingly. Thanks for your prompt reply.

**Comment by benalexau** [comment]
A quick suggestion in case you hadn't come across it already is reviewing [Dmitry's TWS FAQ](http://goo.gl/TRkeRK), which has a lot of commentary around market data limitations and workarounds. It's possible you're hitting one of these quirks.
