### ISSUE TITLE
Error running shell script IBGateway

### ISSUE THREAD

**Issue by nbauma109** [ib-controller/ib-controller#12]
Hello,

I get the following error when running this script

/opt/IBController/IBControllerGatewayStart.sh: line 49: -XX:MaxPermSize=128M: command not found

I think it's due to missing quotes

I would replace 
JAVAOPTS=-Xmx512M -XX:MaxPermSize=128M 
with 
JAVAOPTS='-Xmx512M -XX:MaxPermSize=128M'

Regards,
Nicolas

**Comment by benalexau** [comment]
This is fixed as part of pull request #17. I'll close this ticket accordingly.
