### ISSUE TITLE
Unable to launch additional TWS instances

### ISSUE THREAD

**Issue by beejaya** [ib-controller/ib-controller#120]
I have two IB accounts. I am upgrading to TWS 960 which is the latest version and I am on windows 10 . I have set up the ini and bat files correctly. I launch one TWS instance using its corresponding bat file. When I try to launch the second instance using its bat file nothing happens. There is no error etc. The second one does not launch at all. If I close the first instance, then I am able to launch the TWS for the 2nd account using the bat file that won't work if the first TWS instance is running. What may be the issue?

**Comment by rlktradewright** [comment]
Make sure the two instances use different log file paths.

**Comment by beejaya** [comment]
Perfect. Thanks.
