### ISSUE TITLE
ClosedownAt suggestion is wrong

### ISSUE THREAD

**Issue by mcr-ksh** [ib-controller/ib-controller#124]
the statement in the .ini file is wrong about the suggestion:
"should be: <day hh:mm> eg Friday 22:00"

actually you are parsing like this:
cal.setTime((new SimpleDateFormat("E HH:mm")).parse(shutdownTimeSetting));

which will only accept Friday as "Fr". Else an exception is thrown. 

Best,
ksh

**Comment by rlktradewright** [comment]
In that case, how do you explain the fact that the code has been like that for more than 10 years, and I've always used the suggested format, and it has always worked?

Just to make sure, I just tested it and there is no problem.

**Comment by shevkoplyas** [comment]
(quote from oracle java docs: Class SimpleDateFormat
<http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html#text>
)

[image: Inline image 1]
[image: Inline image 2]

   - *Text:* For formatting, if the number of pattern letters is 4 or more,
   the full form is used; otherwise a short or abbreviated form is used if
   available. For parsing, both forms are accepted, independent of the
   number of pattern letters.

(end of quote)

**Comment by mcr-ksh** [comment]
weird. I had an exception thrown at my server. 

$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
$ java test
all good

$ cat test.java
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.Properties;
import java.util.concurrent.TimeUnit;
import javax.imageio.IIOException;
import javax.transaction.InvalidTransactionException;


class test {
    public static void main(String[] args) {
        String shutdownTimeSetting = "Fr 23:00"; 
        if (shutdownTimeSetting.length() == 0) {
            return;
        } else {
            int shutdownDayOfWeek;
            int shutdownHour;
            int shutdownMinute;
            Calendar cal = Calendar.getInstance();
            try {
                cal.setTime((new SimpleDateFormat("E HH:mm")).parse(shutdownTimeSetting));
                shutdownDayOfWeek = cal.get(Calendar.DAY_OF_WEEK);
                shutdownHour = cal.get(Calendar.HOUR_OF_DAY);
                shutdownMinute = cal.get(Calendar.MINUTE);
                cal.setTimeInMillis(System.currentTimeMillis());
                cal.set(Calendar.HOUR_OF_DAY, shutdownHour);
                cal.set(Calendar.MINUTE, shutdownMinute);
                cal.set(Calendar.SECOND, 0);
                cal.add(Calendar.DAY_OF_MONTH,
                        (shutdownDayOfWeek + 7 -
                         cal.get(Calendar.DAY_OF_WEEK)) % 7);
                if (!cal.getTime().after(new Date())) {
                    cal.add(Calendar.DAY_OF_MONTH, 7);
                }
            } catch (ParseException e) {
		System.out.println("Exception: " + e);
                System.out.println("Invalid ClosedownAt (" + shutdownTimeSetting + ") setting: should be: <day hh:mm> eg Friday 22:00");
                System.exit(1);
            }
            System.out.println("all good");
        }
    }
}

**Comment by shevkoplyas** [comment]
@ksh,

I tried your test.java and as suggested by oracle java docs it gives "all
good" for both strings:
  1) "Fri 23:00"
  2) "Friday 23:00"

but trows an exception for "Fr 23:00" case:

Exception: java.text.ParseException: Unparseable date: "Fr 23:00"
Invalid ClosedownAt (Fr 23:00) setting: should be: eg Friday 22:00

Which is completely opposite result that you see when you mentioned on your
server it will only accept Friday as "Fr".  (it is the only case rejected
by mine:)

I run the above test on my mac:
java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

and on Ubuntu:
java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

with the same result (both refuse to use "Fr", but ok with "Fri" and
"Friday")

**Comment by simonpucher** [comment]
Maybe this is because the "default locale" is different. I am using german as default locale so FR would be fine in that case. FRI not.

**Comment by rlktradewright** [comment]
In view of the lack of further comments, I'll close this.
