### ISSUE TITLE
userguide.pdf: Installing IBController: On Unix: chmod command affecting wider scope than required.

### ISSUE THREAD

**Issue by shevkoplyas** [ib-controller/ib-controller#127]
just a small fix:
in userguide.pdf there's a place:

> you’ll need to make the script f iles executable, using a command similar to this:
> cd /opt
> chmod -R u+x *.sh

which recursively adding executable flag on all files with .sh extension. On my Mac it could affect 320 files:

sudo find /opt -name '*.sh' | wc -l
     320

instead it should "change directory" 1 level deeper:

> cd /opt/IBController
> chmod -R u+x *.sh

Of cause same applies to "userguide.md".

thanks,
Dmitry

**Comment by rlktradewright** [comment]
Thanks. Fixed in next release.

**Comment by rlktradewright** [comment]
Addressed by Release 3.4.0. 

Actually the final version is somewhat different:

```
cd /opt/IBController 
sudo chmod o+x *.sh */*.sh
```
