### ISSUE TITLE
Not working for 963.2c tws

### ISSUE THREAD

**Issue by ssg10** [ib-controller/ib-controller#136]
Hi,
I am using the latest IBcontroller in github.
Updated IBControllerStart.bat to 963.
set TWS_MAJOR_VRSN=963

But, it gave this error:

================================================================================

Starting IBController version 3.2.0 on Sat 02/25/2017 at 21:12:17.65

Operating system:  Microsoft Windows 7 Home Premium  64-bit          6.1.7601  

Arguments:

TWS version = 963
Entry point = ibcontroller.IBController
/TwsPath = C:\Jts
/IbcPath = C:\IBController
/IbcIni = C:\Users\ssg\Documents\IBController\IBController.ini
/Mode = 
/JavaPath = 
/User =
/PW =
/FIXUser =
/FIXPW =

=========================== An error has occurred =============================

Error: TWS version 963 is not installed

**Comment by rlktradewright** [comment]
This is almost certainly because you didn't install the offline version of TWS/Gateway.

IBController doesn't work with the auto-updating versions. This is stated very clearly in the User Guide.

**Comment by ssg10** [comment]
Thanks. it works now

**Comment by twashing** [comment]
I'm having a similar problem with TWS version 963. When I first run the tws workstation, then the ibcontroller, I can see that both started successfully. n particular, the logs are telling me that ibcontroller is successfully logging into tws and controlling its windows.

```
...
------------------------------------------------------------
16:18:15:901 IBController: using default settings provider: ini file is /root/ibcontroller.paper/IBController.ini
16:18:15:901 IBController: using default login manager: getting username and password from args
16:18:15:902 IBController: using default config dialog manager: constructor parameter isGateway=false
16:18:15:902 IBController: using default trading mode manager: constructor parameter args: tradingMode=paper
16:18:15:907 IBController: using default config dialog manager
16:18:15:913 IBController: IBControllerServer is started.
16:18:16:015 IBController: IBControllerServer listening on address: f558f4037b47/172.19.0.2 port: 7462
16:18:16:093 IBController: Creating minimal /root/Jts/jts.ini
16:18:16:093 IBController: Writing required lines to /root/Jts/jts.ini
16:18:16:094 IBController: TWS settings directory is /root/Jts
16:18:18:176 IBController: detected frame entitled: Login; event=Opened
16:18:18:178 IBController: Setting Trading mode = paper
16:18:18:299 IBController: detected frame entitled: Login; event=Activated
16:18:18:312 IBController: Click button: Login
16:18:18:489 IBController: Button now disabled: Login
16:18:19:055 IBController: detected frame entitled: Authenticating...; event=Opened
16:18:19:061 IBController: detected frame entitled: Authenticating...; event=Activated
16:18:30:050 IBController: detected dialog entitled: Downloading settings from server; event=Closed
Jolt logger configuration is done.
LogModuleConfigurator-Init: Log4j Ver2.x found on classpath
LogModuleConfigurator-Init: LogModuleConfigurator initialized with Log4j Verd.x
16:18:42:846 IBController: detected frame entitled: DU542121 Interactive Brokers (Simulated Trading); event=Opened
16:18:42:846 IBController: Found TWS main window
16:18:43:044 IBController: detected frame entitled: Starting application...; event=Closed
16:18:45:325 IBController: detected frame entitled: DU542121 Interactive Brokers (Simulated Trading); event=Activated
16:18:45:373 IBController: detected dialog entitled: Warning; event=Opened
16:18:45:373 IBController: Click button: I understand and accept
16:18:48:898 IBController: detected dialog entitled: API announcements; event=Closed
16:18:48:899 IBController: detected dialog entitled: Warning; event=Closed
```

But when I try to attach to tws from my code, the connection is refused. Without using the UI, how can I configure the following: 

- TWS’ incoming port 
- Enable SocketX and API Clients 
- Accept connections from non-localhost 
- When prompted with an “Accept the connection” dialog box - auto accept, yes 
- Also, how do I know I’m using the OFFLINE version of TWS? This is one the one I’m using on an alpine system: https://download2.interactivebrokers.com/installers/tws/latest-standalone/tws-latest-standalone-linux-x64.sh

**Comment by rlktradewright** [comment]
You can't set these things without using the UI. You only have to configure them once, and the settings will be preserved across sessions. 

Note however that this is NOT true of the demo system: settings for the demo system are reset to the defaults every time you login.

You know you're using the offline version because when you download it from IB's website it tells you very clearly whether it is the offline version (for TWS: there is only an offline version for the Gateway.

Also if it says 'standalone' in the file name, then its the offline version.

And the non-offline versions don't work at all with IBController.

**Comment by shevkoplyas** [comment]
re "how do I know I’m using the OFFLINE version of TWS?"

*2 TWS instances installed on mac OS-X 10.11.5:*

/Users/yourusername/Applications/Trader Workstation/  <---- self updating (*NOT
GOOD *for IBController)

/Users/yourusername/Applications/Trader Workstation *956*/       <------
offline version (*GOOD for IBController*)

*1 TWS installed on Ubuntu 14.04:*

/home/yourusername/Jts/958  <------ offline version (*GOOD for IBController*
)

Long story short - for offline version you should see the version number as
a part of the path to the installation folder. If there's no version number
then you've got wrong version of TWS (not IBController-friendly).

ps: I guess there should be a feature built-into IBController early start
steps where it would use regexp to check path (if 3 digits missing between
"Workstation" and following "/" then report an error and exit). Would
remove 100s of same questions we saw last years.

cheers,
Dmitry

**Comment by twashing** [comment]
Riiight. Ok, that all makes sense. And when I restart my docker container,
with TWS in it, I do notice that the settings persist across restarts.

And based on both of your feedback, I do have the right version of TWS.


Thanks both!!
Tim

**Comment by twashing** [comment]
One other thing. I'm successfully running TWS and IBController. The log
file "*/root/ibcontroller.paper/Logs/ibc-3.2.0_TWS-963_....txt*" , shows me
this:

$ tail -f /root/ibcontroller.paper/Logs/ibc-3.2.0_TWS-963_Sunday.txt
21:56:11:611 IBController: using default settings provider: ini file is
/root/ibcontroller.paper/IBController.ini
21:56:11:611 IBController: using default login manager: getting username
and password from args
21:56:11:611 IBController: *using default config dialog manager:
constructor parameter isGateway=false*
21:56:11:612 IBController: using default trading mode manager: constructor
parameter args: tradingMode=paper
21:56:11:613 IBController: using default config dialog manager
21:56:11:619 IBController: IBControllerServer is started.
21:56:11:686 IBController: IBControllerServer listening on address:
... port: 7462
21:56:11:748 IBController: Creating minimal /root/Jts/jts.ini
21:56:11:748 IBController: Writing required lines to /root/Jts/jts.ini
21:56:11:748 IBController: TWS settings directory is /root/Jts
21:56:13:600 IBController: detected frame entitled: Login; event=Activated
21:56:13:613 IBController: detected frame entitled: Login; event=Opened
21:56:13:614 IBController: Setting Trading mode = paper
21:56:13:681 IBController: Click button: Login
21:56:13:836 IBController: Button now disabled: Login
21:56:14:364 IBController: detected frame entitled: Authenticating...;
event=Opened
21:56:14:371 IBController: detected frame entitled: Authenticating...;
event=Activated
21:56:24:375 IBController: detected dialog entitled: Downloading settings
from server; event=Closed
Jolt logger configuration is done.
LogModuleConfigurator-Init: Log4j Ver2.x found on classpath
LogModuleConfigurator-Init: LogModuleConfigurator initialized with Log4j
Verd.x
21:56:37:828 IBController: detected frame entitled: ... Interactive Brokers
(Simulated Trading); event=Opened
21:56:37:829 IBController: Found TWS main window
21:56:38:037 IBController: detected frame entitled: Starting
application...; event=Closed
21:56:40:631 IBController: detected frame entitled: ... Interactive Brokers
(Simulated Trading); event=Activated
21:56:40:696 IBController: detected dialog entitled: Warning;
event=Activated
21:56:40:696 IBController: detected dialog entitled: Warning; event=Opened
21:56:40:697 IBController: Click button: I understand and accept
21:56:44:036 IBController: detected dialog entitled: API announcements;
event=Closed
21:56:44:037 IBController: detected dialog entitled: Warning; event=Closed
21:56:44:121 IBController: detected frame entitled: Daily Lineup: Sunday,
March 12, 2017; event=Opened
21:56:44:124 IBController: detected dialog entitled: API announcements;
event=Opened


But when I try to connect, using the correct hostname and port, the call
just hangs there.

(.eConnect client hostname port reqId)



If I were to manually run TWS and click through all the dialogs, I'd have
to manually "accept" an incoming connection.


​

But I can't seem to get IBController to "accept" that for me. The only clue
I think might be related, is the log output where ibcontroller says:
"*IBController:
using default config dialog manager: constructor parameter isGateway=false*"
. Is that related? Is there a way to have ibcontroller accept that incoming
connection?

Thanks
Tim

**Comment by rlktradewright** [comment]
Look in IBController.ini at the `AcceptIncomingConnectionAction` setting.

While you're there, you might as well take the time to familiarise yourself with all the other settings so you know what else it can do for you.

**Comment by twashing** [comment]
That was fast :)

I actually do have that set in my *IBController.ini* file. I double-checked
that that's the setting when IBController is run. Does '*accept*' need to
be in quotes?

AcceptIncomingConnectionAction=accept

**Comment by twashing** [comment]
Hmm, but I also just found this.

...
Starting IBController with this command:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp ... -Xmx768m
ibcontroller.IBController /root/ibcontroller.paper/IBController.ini *** ***
paper

22:46:41:574 IBController: *Properties file
/root/IBController/IBController.ini not found*
System Properties
------------------------------------------------------------
java.runtime.name = OpenJDK Runtime Environment
...


Seems strange that it's looking for "*/root/IBController/IBController.ini*",
when I explicitly gave it my custom "
*/root/ibcontroller.paper/IBController.ini*". I probably missed a setting
somewhere?


Tim Washington
Interruptsoftware.com <http://interruptsoftware.com>
415.283.8889

**Comment by rlktradewright** [comment]
The trouble is, you're not following the instructions!

The fact that it says 'java.runtime.name = OpenJDK Runtime Environment' gives you away. TWS doesn't work with OpenJdk, only with the Oracle JDK. (It may look like it's working with OpenJDK, but I assure you that it doesn't.)

If you follow the instructions, it will use the Oracle JDK that's included in the TWS installation.

The instructions in the User Guide are carefully crafted so that new users can be guaranteed to get a working installation connecting to the demo system. Once you have that, then you'll know it works (and I 100% guarantee you that it does!).  Then you can start tweaking it to suit your needs, and if something stops working then you'll know it was because you changed something incorrectly.

**Comment by twashing** [comment]
Hmm, that sounds fair. I knew it had to be something I missed. Let me give
that a go...

**Comment by twashing** [comment]
Yep. You were exactly right. Using the built-in Oracle JDK fixed
everything. Now everything's copacetic.

I suppose I owe you a beer :)


Cheers
Tim

**Comment by leecallen** [comment]
Okay I know this is an **_extremely_** FAQ from noobs. But I swear I have read the users guide carefully, and followed the installation steps meticulously, and yet IBController says it can't find TWS version 963.

Windows 10.

I installed TWS from a link on IB's web page labelled "OFFLINE TWS", the zip file was named:
tws-stable-standalone-windows-x64.zip

The resulting unzipped directory structure contains:
C:\Jts\963

I don't know of any other way to confirm this is the offline mode, but from what I have read in this thread it is.

My IBControllerPaper.init contains:
TradingMode=paper
IbDir=C:\\JtsPaper
(as well as valid username, password, etc)

My IBControllerStartPaper.bat contains:
set TWS_MAJOR_VRSN=963
set IBC_INI=%HOMEDRIVE%%HOMEPATH%\Documents\IBController\IBControllerPaper.ini
set TRADING_MODE=
set IBC_PATH=%SYSTEMDRIVE%\IBController
set TWS_PATH=%SYSTEMDRIVE%\Jts     
set LOG_PATH=%IBC_PATH%\Logs

and the resulting log file says:
Error: TWS version 963 is not installed 
You must install the offline version of TWS/Gateway
IBController does not work with the auto-updating TWS/Gateway

I have run the TWS program manually from that locatino (C:\Jts\963), it works fine.

Help, please???

**Comment by rlktradewright** [comment]
First, please note [IBController is now effectively superseded by IBC](https://github.com/IbcAlpha/IBC). You can read about the reasons for this change [here](https://groups.io/g/ibcalpha/message/570). You should probably consider switching to IBC. I'm no longer providing support to this repository (so I won't be adding any further updates to this post).

Next, it's not good form to resurrect an issue that has been closed for almost a year. Just start a new one. You can always refer to the old one if you think there is definitely something relevant in it: in this case there probably isn't.

Thirdly, it's far more helpful to attach the log files, start scripts etc to your post than just quote the bits that you think are relevant (note: _attach_ the files, don't quote their full content inline): the log files contain a lot of information that I think is relevant, even if you don't.

Finally please read the notes in IBController.ini regarding the IbDir setting: you need double backslashes. However I doubt that is the cause of your problem.

**Comment by leecallen** [comment]
I was not aware of IBC. Thank you for responding and pointing that out.
