### ISSUE TITLE
improvement: IBController can check if user installed expected offline/standalone TWS version

### ISSUE THREAD

**Issue by shevkoplyas** [ib-controller/ib-controller#138]
Expected offline TWS version should have the version number as a part of the path to the installation folder. IBController might check that before trying to run TWS.

Since configured IBController already have the knowledge of TWS_MAJOR_VRSN and TWS_PATH we can add the check into IBControllerStart.sh starter script which does following 2 checks:
  1) user didn't forget to specify version number (in below example it simple check "not empty string", but might be more precise and check "represent int number >0 and has 3 digits"
  2) path to TWS installation folder include that version number and exist on the filesystem.

```
JAVA_PATH=


#              PLEASE DON'T CHANGE ANYTHING BELOW THIS LINE !!
#==============================================================================

# check if TWS version wis specified (must be present in TWS offline version)
if [ "${TWS_MAJOR_VRSN}" == "" ]; then
    echo "error: please set TWS_MAJOR_VRSN variable in $0 script" >&2
    exit 1
fi

# check if TWS directory exit and it has 3-digit version number in it
TWS_OFFLINE_DIR="${TWS_PATH}/${TWS_MAJOR_VRSN}"
if [ ! -d "${TWS_OFFLINE_DIR}" ]; then
    echo
    echo "error: directory '${TWS_OFFLINE_DIR}' does not exist." >&2
    echo "IBController can only work with 'offline' (also known as 'standalone')" >&2
    echo "version of TWS (or IBGateway). One of distinct features of 'offline' version" >&2
    echo "is the presence of TWS version number in the installation directory path." >&2
    echo "Example of 'offline' TWS version default path:" >&2
    echo "   /home/your_user_name/Jts/963" >&2
    echo
    exit 1
fi



#   Notes:
#
```

Most probably the gramma should be changed.
thanks for great project,
cheers,
Dmitry Shevkoplyas

**Comment by rlktradewright** [comment]
@shevkoplyas I've already made a similar update (to IBController.sh and IBController.bat rather than the top-level scripts), but I haven't published it yet.

The error message I used is rather less detailed than yours. It simply says:

```
if [[ ! -e "$jars" ]]; then
	error_exit $E_TWS_VERSION_NOT_INSTALLED "TWS version $tws_version is not installed: can't find $jars" \
	                                        "You must install the offline version of TWS/Gateway" \
                                            "IBController does not work with the auto-updating TWS/Gateway"
fi
```

I'll consider beefing it up a bit along the lines you suggested.

Note that there is already an error message from IBController.sh/IBController.bat if the major version number isn't supplied..
