### ISSUE TITLE
Rename logs to specific dates instead of weekday

### ISSUE THREAD

**Issue by dandv** [ib-controller/ib-controller#139]
Thanks for publishing IBController! I've been running it for a few months now and have noticed that I have only three log files:

```
ibc-3.2.0_GATEWAY-952_Saturday.txt
ibc-3.2.0_GATEWAY-952_Tuesday.txt
ibc-3.2.0_GATEWAY-952_Wednesday.txt
```

That naming scheme will obviously lead to logs overwriting older ones every week, which makes troubleshooting issues older than a week impossible.

Any chance to rename the log files from under TWS to include YYYYMMDD, even if only when `CloseDownAt` is set?

**Comment by rlktradewright** [comment]
And do you find you often need to troubleshoot issues older than a week? If I have an issue with either my paper or live TWS/Gateway, everything else is dropped and investigating it becomes top priority. Why would I want to leave it over the weekend?

This scheme prevents the inevitable build-up of a huge mass of log files that occurs with a date-based scheme. It's also consistent with TWS and the Gateway.

I don't want to force users into doing log management. If it's important to you to keep logs for more than a week, you could easily set up a Scheduled Task or cron to copy them somewhere else.

**Comment by dandv** [comment]
> And do you find you often need to troubleshoot issues older than a week?

I may be gone for over a week.

Or the issue may be worked around by the daily restarts.

Or I don't have time to dig into it for another week.

Etc.

**Comment by rlktradewright** [comment]
Then do what I suggested and make provision for your old logs to be preserved. It's not rocket science.

The current logging mechanism works well, and I see no reason to change it.
