### ISSUE TITLE
ibcontroller.IBController not found

### ISSUE THREAD

**Issue by eliquinox** [ib-controller/ib-controller#142]
First of all, thank you for your efforts to open source such a great resource.
I have the following issue, when I run IBControllerStart.sh, I get the following error:

```
Error: Could not find or load main class ibcontroller.IBController
IBController finished

```

My first hunch is that the script can not find a directory for a certain java file, but I wanted to confirm. And if so, what file is it and how do I specify the path to it?

I appreciate your help.

Thanks

**Comment by benalexau** [comment]
Few quick questions:

* Is that the full output?
* Which version of TWS did you download and install?
* Which version of IBController are you trying?
* Which operating system are you using?
* Did you remember to edit the `IBControllerStart.sh` to reflect the installation locations?
* Did you go through the "Checklist" and "Installing IBController" sections in the [user guide](https://github.com/ib-controller/ib-controller/blob/master/userguide.md)?

**Comment by eliquinox** [comment]
Hey benelaux,

Thank you for your response.
1. Below is the full output

```
Generating the classpath
Classpath=/home/eliquinox/Jts/964/jars/jts4launch-964.jar:/home/eliquinox/Jts/964/jars/locales.jar:/home/eliquinox/Jts/964/jars/log4j-api-2.5.jar:/home/eliquinox/Jts/964/jars/log4j-core-2.5.jar:/home/eliquinox/Jts/964/jars/total-2015c.jar:/home/eliquinox/Jts/964/jars/twslaunch-964.jar:/home/eliquinox/Jts/964/jars/twslaunch-install4j-1.8.jar:/home/eliquinox/opt/IBController/IBController.jar

Generating the JAVA VM options
Java VM Options=-Xmx768m

Determining the location of java executable
Location of java executable=/home/eliquinox/.i4j_jres/1.8.0_60_64/bin

Starting IBController with this command:
/home/eliquinox/.i4j_jres/1.8.0_60_64/bin/java -cp /home/eliquinox/Jts/964/jars/jts4launch-964.jar:/home/eliquinox/Jts/964/jars/locales.jar:/home/eliquinox/Jts/964/jars/log4j-api-2.5.jar:/home/eliquinox/Jts/964/jars/log4j-core-2.5.jar:/home/eliquinox/Jts/964/jars/total-2015c.jar:/home/eliquinox/Jts/964/jars/twslaunch-964.jar:/home/eliquinox/Jts/964/jars/twslaunch-install4j-1.8.jar:/home/eliquinox/opt/IBController/IBController.jar -Xmx768m ibcontroller.IBController /home/eliquinox/IBController/IBController.ini  

Error: Could not find or load main class ibcontroller.IBController
IBController finished

```

2. Version 964
3. The most recent one.
4. Linux Ubuntu 16.04
5. Yes, I made sure to reflect the locations.
6. Yep.

Cheers

**Comment by rlktradewright** [comment]
This is by no means the full output! What do you think the log file is for? It contains far more than what you've sent. It would be far preferable to just attach the log file when you raise an issue like this.

However, from the information you've given it looks like IBController.jar isn't actually in /home/eliquinox/opt/IBController/

**Comment by eliquinox** [comment]
It is solved!
Shell scripts was pointing to another directory for IBController.jar.
Fixed it now.
