### ISSUE TITLE
Can't find suitable Java installation

### ISSUE THREAD

**Issue by coin-au-carre** [ib-controller/ib-controller#145]
According to the user guide : 

> TWS version 950 and earlier required Java to be explicitly installed on the computer. However starting with TWS 952, the TWS installers for Windows and Linux include a hidden version of Java which Interactive Brokers have used for developing and testing TWS. This version also runs IBController perfectly, and the IBController scripts ensure that it is used.

I am using IB GW 963 so I assumed I could let empty the `JAVA_PATH=` in `IBControllerGatewayStart.sh`.  However, executing the latter script gives me: 

```
Determining the location of java executable
Found java executable in PATH
System java java is not from Oracle, won't use it
=========================== An error has occurred =============================
Error: Can\'t find suitable Java installation
```

I have then set up manually the path with `JAVA_PATH=/usr/lib/jvm/java-8-openjdk/jre/bin/` on an Archlinux and the IBController works fine.
However when I put on a Debian server with an older JAVA version `JAVA_PATH=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin` and I get the following error: 

> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 12:47:38:679 IBController: Can't find the Gateway entry point: ibgateway.GWClient.main. Gateway is not correctly installed.
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> java.lang.UnsupportedClassVersionError: ibgateway/GWClient : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	at ibcontroller.IBController.startGateway(Unknown Source)
> 	at ibcontroller.IBController.startTwsOrGateway(Unknown Source)
> 	at ibcontroller.IBController.load(Unknown Source)
> 	at ibcontroller.IBGatewayController.main(Unknown Source)
> IBGateway finished

The IB GW works fine by itself (without IBController) on Debian so my guess is that hidden Java version is used. Therefore I think that the code that  the `Error: Can\'t find suitable Java installation` should now be ignored as told in the comments.

>   JAVA_PATH
>     IB's installer for TWS/Gateway includes a hidden version of Java which 
>     IB have used to develop and test that particular version. This means that
>     it is not necessary to separately install Java. If there is a separate
>     Java installation, that does not matter: it won't be used by IBController 
>     or TWS/Gateway unless you set the path to it here. You should not do this 
>     without a very good reason.

**Comment by coin-au-carre** [comment]
OK I could fix the issue with this line in IBController.sh:

`tws_installer="$tws_path/ibgateway/$tws_version/.install4j"`

I will pull a request when I have time.

**Comment by rlktradewright** [comment]
There is no line in IBController.sh that begins

`tws_installer=`

The only line that looks similar is this::

`tws_install4j="${tws_path}/${tws_version}/.install4j"`

and it would be incorrect to modify that in the way you suggest.

Have you modified IBController.sh? It works perfectly 'out-of-the box'. Please revert back to the original files and try again.

**Comment by coin-au-carre** [comment]
You are right I thought I had the up to date version but you fixed the bug after the release 3.2. My apologies :

https://github.com/ib-controller/ib-controller/blob/418b979df3740c4eb51e418c6c0c714b680e7ada/resources/Scripts/IBController.sh

**Comment by nikolom** [comment]
I got this error: Can\'t find suitable Java installation. Also: Determining the location of java executable
Found java executable in PATH
System java java is not from Oracle, won't use it

I have Java here: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Also, I have: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
which is 1.8.0_131.

Any ideas? Thank You.

**Comment by rlktradewright** [comment]
If you set up IBController following the instructions in the User Guide, you cannot possibly get this error. 

Please reply attaching the IBController log file (all of it!).

**Comment by nikolom** [comment]
Richard, I did read the user guide. I attach the log file.
Thank You.

Martin


On Mon, Jun 19, 2017 at 8:50 AM, Richard L King <notifications@github.com>
wrote:

> If you set up IBController following the instructions in the User Guide,
> you cannot possibly get this error.
>
> Please reply attaching the IBController log file (all of it!).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ib-2Dcontroller_ib-2Dcontroller_issues_145-23issuecomment-2D309445637&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=kfFxILKzGU1aUGekHi3sKQ&m=5oaI8DxU7R22VFFP7pf_JuKQuImvIb15I2k65oBFXDg&s=caDDLG2eNvh3wD35SisZew3EH4nckVY2KNU_IEuH8xo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ab-5F9SdwZpbpGlK9h4y5Pt7a6OgoskJI4ks5sFny-2DgaJpZM4NVKKG&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=kfFxILKzGU1aUGekHi3sKQ&m=5oaI8DxU7R22VFFP7pf_JuKQuImvIb15I2k65oBFXDg&s=IKexbG6QrB4CR4qbRYPu3F3CVaNu_twzyiphBU9aVmA&e=>
> .
>


================================================================================

date: illegal option -- I
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Starting IBController version 3.2.0 on  at 15:41:53

Operating system: Darwin MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Thu Jun 16 19:58:21 PDT 2016; root:xnu-2782.50.4~1/RELEASE_X86_64 x86_64

Arguments:

TWS version = 966
Entry point = ibcontroller.IBController
--tws-path = /Users/nikolom/Applications
--tws-settings-path = /Users/nikolom/Jts
--ibc-path = /opt/IBController
--ibc-ini = /Users/nikolom/IBController/IBController.ini
--mode = 
--java-path = 
--user =
--pw =

=================================
Generating the classpath
Classpath=/Users/nikolom/Applications/Trader Workstation 966/jars/jts4launch-966.jar:/Users/nikolom/Applications/Trader Workstation 966/jars/locales.jar:/Users/nikolom/Applications/Trader Workstation 966/jars/log4j-api-2.5.jar:/Users/nikolom/Applications/Trader Workstation 966/jars/log4j-core-2.5.jar:/Users/nikolom/Applications/Trader Workstation 966/jars/total-2017.jar:/Users/nikolom/Applications/Trader Workstation 966/jars/twslaunch-966.jar:/Users/nikolom/Applications/Trader Workstation 966/jars/twslaunch-install4j-1.8.jar:/opt/IBController/IBController.jar

Generating the JAVA VM options
Java VM Options=-Xmx768m

Determining the location of java executable
Found java executable in PATH
System java java is not from Oracle, won't use it

=========================== An error has occurred =============================



Error: Can\'t find suitable Java installation

**Comment by rlktradewright** [comment]
Ok, my statement in my previous post was over-optimistic! It should have said 'If you set up IBController following the instructions in the User Guide, you cannot possibly get this error, provided that you use Release 3.3.0-beta.3 on macOS'. 

So please try again using Release 3.3.0-beta.3.

When the 3.2.0 release was made, the macOS scripts were in their infancy, and at that time they did not make use of the hidden Java installation included in the TWS installer; in fact I believe that at that time, IB didn't actually include the hidden Java for the macOS installer, so the IBController user had to install Java manually for macOS. But with current TWS versions, the hidden Java is included and the revised scripts in 3.3.0-beta.3 make proper use of it. 

By the way, the error message you got is saying that it did find a Java installation, but it wasn't Oracle java, and TWS doesn't work properly with non-Oracle Java.

Apologies for the confusion.

**Comment by nikolom** [comment]
Thank you very much, Richard. I will come back to it soon.

**Comment by rlktradewright** [comment]
Closing this due to lack of further comment.
