### ISSUE TITLE
IBController fails: problem creating jts.ini

### ISSUE THREAD

**Issue by rlktradewright** [ib-controller/ib-controller#155]
IBController Version 3.4.0 fails to start and the logfile contains a message similar to this:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
09:30:13:155 IBController:  Problem creating C:\MyTwsSettings\jts.ini: C:\MyTwsSettings\jts.ini (No such file or directory)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rlktradewright** [comment]
This error is caused by setting `IbDir` in IBController.ini to a directory path that does not already exist.

A workaround is simply to ensure the directory exists before running IBController.

Alternatively, use version 3.4.2 of `IBController.jar`. This version automatically creates the specified directory if it doesn't already exist. You can download it from [here](https://github.com/ib-controller/ib-controller/tree/master/resources). You should also download the `version` file to ensure that your IBController logfiles contain the correct version information.

**Comment by benalexau** [comment]
Thanks Richard, I confirm 3.4.2 automatically creates the directory if not present.

I have updated the Arch Linux package to no longer create the directory in commit https://aur.archlinux.org/cgit/aur.git/commit/?h=ib-controller&id=c7f23a907409c51ddf32db857453ff9dbf8df6f6

**Comment by rlktradewright** [comment]
Closing this due to lack of further comment.
