### ISSUE TITLE
Stopping IBController with Task Scheduler

### ISSUE THREAD

**Issue by hokavs** [ib-controller/ib-controller#164]
Hi there,

When manually using the IBControllerStop.bat file, it works like a charm (after IBControllerStart.bat opened TWS for me). However, when I add the file to the Windows 10 Task manager, it keeps hanging in a telnet screen, and it's not shutting down TWS. Maybe I have to be more patient and wait longer, but it's strange that manually it works instantly, while through Task Manager it does nothing, not even after an hour.

Yes, Telnet is activated/enabled. So what am I doing wrong?
Thanks in advance!

**Comment by rlktradewright** [comment]
I presume you mean Task Scheduler rather than Task Manager.

I can confirm that I get the same behaviour as you. I suspect this is because when the .bat file is run from Task Scheduler, for some reason it doesn’t get the focus, so the script that sends the keys is sending them somewhere else. 

At the moment, I don’t know what to suggest. I’ll have to think about this.

**Comment by rlktradewright** [comment]
On further investigation, I was incorrect: it works perfectly on Windows 10.

Make sure that your IBControllerStop.bat runs telnet like this:

`start telnet %ServerAddress% %IBControllerServerPort%` 

The first time I tried it, I was on a machine that had an old (unreleased) version of IBControllerStop.bat which didn't use the `start` command, and without that it doesn't work.

Also make sure that the 'Start in (optional)' field in the action definition for the scheduled task is set to the folder that contains the IBControllerStop.bat file (normally C:\IBController).

**Comment by rlktradewright** [comment]
@hokavs 

Any further comments on this? If not, please close the issue.

**Comment by hokavs** [comment]
I was incorrect too; my server was running Windows 2016 instead of Windows 10.
The bat file already had that command line that you advised. 
However,the "Start in" field seemed to make the difference. It seems to work now.
