### ISSUE TITLE
Unable to Run IBcontroller and IB gateway inside Docker Container

### ISSUE THREAD

**Issue by nyxynyx** [ib-controller/ib-controller#165]
Following the README.md instructions to run both IBController and IB Gateway in a docker container, I created a `Dockerfile` based on [QuantConnect's LeanFoundation](https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation).

Next I build the image and  tried to start it

    docker run 3a10c3adec74 

It outputs

    *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
    *** Running /etc/rc.local...
    *** Booting runit daemon...
    *** Runit started as PID 7

After connecting to the container's bash, I cannot seem to find `IBControllerStart.sh` and `IBControllerGatewayStart.sh`. How can I start/restart IBController, and how can I tell if IBController is running?

**Comment by rlktradewright** [comment]
@jaredbroad this sounds like one for you!

**Comment by jaredbroad** [comment]
Hey @nyxynyx -- please post your custom Dockerfile and complete logs to the open source support for LEAN: https://groups.google.com/forum/#!forum/lean-engine
