### ISSUE TITLE
No errors after running IBControllerGatewayStart.sh, but IB Gateway did not start?

### ISSUE THREAD

**Issue by vertangelx** [ib-controller/ib-controller#167]
Im troubled trying to get IBController and IB Gateway running on an Ubuntu system.

After completing the installation steps, and editing `TWS_MAJOR_VRSN`, I ran `IBControllerGatewayStart.sh` and the green banner shows up

	+==============================================================================
	+
	+ IBController version 3.2.0.2
	+
	+ Running GATEWAY 968
	+
	+ Diagnostic information is logged in:
	+
	+ /home/vert/IBController/Logs/ibc-3.2.0.2_GATEWAY-968_Wednesday.txt
	+
	+

But when I check what ports are open, I only see the port for IBController and not the IB gateway. 

	$ lsof -i
	COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
	java    12634 vert   13u  IPv6 264082      0t0  TCP vvv.c.polished-leaf-165119.internal:7462 (LISTEN)

Why is the IB gateway not starting? 

Do you also adjust the IB gateway port by editing the value of `LocalServerPort` in `jts.ini`?

**Comment by rlktradewright** [comment]
You configure all aspects of the API via TWS or Gateway's Global Configuration dialog.

IBController is not a TWS/Gateway configuration mechanism, except in very special cases where it is necessary. It is the user's responsibility to configure TWS/Gateway to meet their requirements..

**Comment by vertangelx** [comment]
I have configured IB Gateway v968 to my liking on Windows and copied the Jts.ini into the Linux system `~/Jts` directory.

However it seems that IBController did not manage to start IB gateway on the Linux system? The output of `lsof` is in my previous comment. 

How should I troubleshoot this problem? Thank you.

**Comment by rlktradewright** [comment]
The Gateway doesn't store most of its settings in Jts.ini: only a few things that need to be known before the user logs in.

If you look in the C:\Jts folder on your Windows system, you'll see subfolders with names like this:

djkknie
djjifxfwn

These are per-user folders that store the Gateway and TWS settings (in files called tws.xml and ibg.xml, together with per-day copies of them). The first folder is for my live login, the second for my paper login (your folder names may be different). If you look inside these xml files with something like Notepad++ (or other text editor) you'll see the vast amount of configuration data stored, and then you can perhaps see why IBController doesn't undertake to manage it all!

So you must make sure you copy the relevant folder over to your Linux system.

Note that if you login to a demo account, you will get a different folder name each time (this is because you are actually randomly allocated one of many different demo accounts each time you login to demo). This means that this folder copying approach will not work reliably for the demo account: you will have to just accept the defaults

**Comment by vertangelx** [comment]
Thank you for the explanation. I have located the latest d***** subfolder in C:\Jts that I want to use on the Linux system. 

However where should I copy it too? Do I copy the contents to **IBController program files** whose default path is `/opt/IBController` according to the user guide?

**Comment by rlktradewright** [comment]
No, copy it to the ~/Jts folder on Linux where the Gateway is installed.

All you're trying to do is to replicate the Gateway installation from your Windows system to your Linux system (apart from the Gateway program files, which won't work on Linux).

This has nothing to do with IBController.

**Comment by vertangelx** [comment]
I have copied the d***** folder to `~/Jts`, and ran `IBControllerGatewayStart.sh` again after killing the previous process that was listening to port 7462.

However I am still unable to connect to IB Gateway, and `lsof -i` only show port 7462 open, not the IB gateway port 4000.

What do you suggest that I try next?

**Comment by vertangelx** [comment]
Here's the output of IBController logs


	================================================================================

	Starting IBController version 3.2.0.2 on 2017-11-02 at 20:21:14

	Operating system: Linux aaa 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

	Arguments:
	a
	TWS version = 968
	Entry point = ibcontroller.IBGatewayController
	--tws-path = /home/vert/Jts
	--tws-settings-path = /home/vert/Jts
	--ibc-path = /home/vert/IBController
	--ibc-ini = /home/vert/IBController/IBController.ini
	--mode = 
	--java-path = 
	--user =
	--pw =
	--fix-user =
	--fix-pw =

	=================================
	Generating the classpath
	Classpath=/home/vert/Jts/ibgateway/968/jars/jts4launch-968.jar:/home/vert/Jts/ibgateway/968/jars/locales.jar:/home/vert/Jts/ibgateway/968/jars/log4j-api-2.5.jar:/home/vert/Jts/ibgateway/968/jars/log4j-core-2.5.jar:/home/vert/Jts/ibgateway/968/jars/total-2017.jar:/home/vert/Jts/ibgateway/968/jars/twslaunch-968.jar:/home/vert/Jts/ibgateway/968/jars/twslaunch-install4j-1.8.jar:/home/vert/IBController/IBController.jar

	Generating the JAVA VM options
	Java VM Options=-Xmx768m

	Determining the location of java executable
	Found java executable in PATH
	Location of java executable=/usr/bin

	Starting IBGateway with this command:
	/usr/bin/java -cp /home/vert/Jts/ibgateway/968/jars/jts4launch-968.jar:/home/vert/Jts/ibgateway/968/jars/locales.jar:/home/vert/Jts/ibgateway/968/jars/log4j-api-2.5.jar:/home/vert/Jts/ibgateway/968/jars/log4j-core-2.5.jar:/home/vert/Jts/ibgateway/968/jars/total-2017.jar:/home/vert/Jts/ibgateway/968/jars/twslaunch-968.jar:/home/vert/Jts/ibgateway/968/jars/twslaunch-install4j-1.8.jar:/home/vert/IBController/IBController.jar -Xmx768m ibcontroller.IBGatewayController /home/vert/IBController/IBController.ini  

	System Properties
	------------------------------------------------------------
	java.runtime.name = Java(TM) SE Runtime Environment
	sun.boot.library.path = /usr/lib/jvm/java-8-oracle/jre/lib/amd64
	java.vm.version = 25.151-b12
	java.vm.vendor = Oracle Corporation
	java.vendor.url = http://java.oracle.com/
	path.separator = :
	java.vm.name = Java HotSpot(TM) 64-Bit Server VM
	file.encoding.pkg = sun.io
	user.country = US
	sun.java.launcher = SUN_STANDARD
	sun.os.patch.level = unknown
	java.vm.specification.name = Java Virtual Machine Specification
	user.dir = /home/vert/Jts
	java.runtime.version = 1.8.0_151-b12
	java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
	java.endorsed.dirs = /usr/lib/jvm/java-8-oracle/jre/lib/endorsed
	os.arch = amd64
	java.io.tmpdir = /tmp
	line.separator = 

	java.vm.specification.vendor = Oracle Corporation
	os.name = Linux
	sun.jnu.encoding = UTF-8
	java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
	java.specification.name = Java Platform API Specification
	java.class.version = 52.0
	sun.management.compiler = HotSpot 64-Bit Tiered Compilers
	os.version = 4.10.0-37-generic
	user.home = /home/vert
	user.timezone = Etc/UTC
	java.awt.printerjob = sun.print.PSPrinterJob
	file.encoding = UTF-8
	java.specification.version = 1.8
	java.class.path = /home/vert/Jts/ibgateway/968/jars/jts4launch-968.jar:/home/vert/Jts/ibgateway/968/jars/locales.jar:/home/vert/Jts/ibgateway/968/jars/log4j-api-2.5.jar:/home/vert/Jts/ibgateway/968/jars/log4j-core-2.5.jar:/home/vert/Jts/ibgateway/968/jars/total-2017.jar:/home/vert/Jts/ibgateway/968/jars/twslaunch-968.jar:/home/vert/Jts/ibgateway/968/jars/twslaunch-install4j-1.8.jar:/home/vert/IBController/IBController.jar
	user.name = vert
	java.vm.specification.version = 1.8
	sun.java.command = ibcontroller.IBGatewayController /home/vert/IBController/IBController.ini
	java.home = /usr/lib/jvm/java-8-oracle/jre
	sun.arch.data.model = 64
	user.language = en
	java.specification.vendor = Oracle Corporation
	awt.toolkit = sun.awt.X11.XToolkit
	java.vm.info = mixed mode
	java.version = 1.8.0_151
	java.ext.dirs = /usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext
	sun.boot.class.path = /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes
	java.vendor = Oracle Corporation
	file.separator = /
	java.vendor.url.bug = http://bugreport.sun.com/bugreport/
	sun.io.unicode.encoding = UnicodeLittle
	sun.cpu.endian = little
	sun.cpu.isalist = 
	------------------------------------------------------------
	20:21:14:887 IBController: using default settings provider: ini file is /home/vert/IBController/IBController.ini
	20:21:14:887 IBController: using default login manager: getting username and password from args but not found. Will get from settings
	20:21:14:887 IBController: using default config dialog manager: constructor parameter isGateway=true
	20:21:14:889 IBController: using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
	20:21:14:893 IBController: using default config dialog manager
	20:21:14:899 IBController: IBControllerServer is started.
	20:21:15:010 IBController: IBControllerServer listening on address: aaa/10.142.0.2 port: 7462
	20:21:15:023 IBController: TWS settings directory is ../Jts
	20:21:16:151 IBController: Getting config dialog
	20:21:16:151 IBController: Creating config dialog future

**Comment by rlktradewright** [comment]
Is that the whole of your logfile?

If not, please include the whole thing, but don't quote the contents, just attach the file itself.

If that is the whole thing, then it appears that the Gateway is not starting properly at all. There should be a file called ~Jts\launcher.log. Have a look in there and see if there's something that might indicate what's wrong, or attach it to your reply for me to look at.

By the way, it looks as though you've used the ForceTwsApiPort setting in your IBController.ini file. If you configured the API port number on your Windows system using the Gateway's configuration dialog (as you should have done), then that will be included in the settings folder you copied over to Linux. So there's no reason to use ForceTwsApiPort  which is only intended for special circumstances where the configured value needs to be overridden for some reason. It won't do any harm, but why do unnecessary stuff?

**Comment by vertangelx** [comment]
Yes thats the entire log file. Managed to get IB Gateway to run by using another .sh script that runs IBController in headless mode using xvfb.

Now `lsof -i` shows IBController listening to both and IB Gateway listening to 4001. I am able to connect locally to the local IB Gateway. 

	COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
	java    23736 vert   13u  IPv6 393304      0t0  TCP vvv.c.polished-leaf-165119.internal:7462 (LISTEN)
	java    23736 vert   26u  IPv6 393433      0t0  TCP *:4001 (LISTEN)

But when I try to connect remotely to the IB Gateway, the connection times out!

I have set `IBController.ini` to include the following values

    [IBGateway]
    ...
    TrustedIPs=0.0.0.0
    ...

On google GCP console, I have set the firewall to open port 4001. Am I missing out something?

**Comment by rlktradewright** [comment]
So did you look at ~Jts\auncher.log like I asked?

I suspect that the previous log was so short because you didn't have xvfb or other X11 server running, and so Gateway was just hanging as it was unable to 'display' its user interface.

Please don't mess with Jts.ini - you never need to touch it. The TrustedIPs setting in there does nothing (as far as I'm aware). The list of Trusted IPs is maintained in ibg.xml. along with all the other settings, so you need to set these up on your Windows system before you copy the folder over to Linux. Please try to understand this: Jts.ini only contains settings that are not relevant to a specific user. Anything that different users might want to configure differently is in ibg.xml, and has to be set up via the configuration dialog.

The errors you're getting are consistent with the Trusted IPs list not being set up, so once you've done that hopefully it will be ok.

**Comment by vertangelx** [comment]
Yes you are right to suggest looking at `~Jts/launcher.log`, that is where I discovered `xvfb` is needed.

I setup trusted IPs in IB gateway on my Windows computer, and copied the new d*** folder over to my linux system `~/Jts`. `ibg.xml` does contain `allowOnlyLocalhost="false"` and `0.0.0.0` under `trustedIPAddresses`

	<ApiSettings varName="api" dde="false" readOnlyApi="false" allowOnlyLocalhost="false" socketClient="false" autoOpenOrdDonwload="true" port="4001" includeFxPositions="true" prepareDailyPnl="true" includeContinuousUpdateChanges="true" sendMessagesInEnglish="false" sendMessagesTranslated="true" logLevel="2" useNegativeAutoRange="true" overridePrecautionaryConstraints="false" bypassBondWarning="false" bypassYtwWarning="false" bypassCalledBondWarning="false" bypassSameActionPairTradeWarning="false" masterClientID="-1" acceptLargeSize="false" showApiMsg="false" includeMktData="false" createApiMsgLogFile="false" showIBGConsole="false" aPINotAllowedShownAfterDenyAPI="false" slowBufferTimeout="30" syncAccounts="false" multichartNetDoNotShowTime="0" multichartDoNotShowTime="0" verifiedAppPortRangeStart="7000" verifiedAppPortRangeEnd="8000" timeOfVerifiedAppShutdown="0" portOfVerifiedAppShutdown="0" exposeEntireTradingSchedule="true">

		<ListOfStrings varName="trustedIPAddresses">
			<String>127.0.0.1</String>
			<String>0.0.0.0</String>
		</ListOfStrings>

`IBController.ini` has the following value set

    AcceptIncomingConnectionAction=accept


However after restarting IBController (and IB Gateway), I am still not able to connect remotely to IB Gateway.

`tcpdump` shows clearly that my request packets are hitting the port that IB Gateway is listening to (also checked using `lsof`), so its not a firewall problem or entering the wrong ip/port in my script that connects to IB Gateway.

The IBController logs do not show anything related to a remote API connection .

I know this is may likely be outside of IBController, but do you or anyone knows what else is needed to get IB Gateway to allow remote connections?

**Comment by rlktradewright** [comment]
What is 0.0.0.0? This is not a valid IP address.

Also you've got `allowOnlyLocalhost="false"`, but the only valid address in your Trusted IP Addresses list is `127.0.0.1` which IS `localhost`.

Perhaps you think 0.0.0.0 means any address? Well it doesn't. You have to put the exact IP addresses you want to allow to connect in the Trusted IP Addresses list: there are no wildcards or abbreviations allowed.

Do me a favour: get the thing set up and working properly on Windows, with whatever computer is running your API program connecting in properly. Only then copy the settings folder over to Linux.
