### ISSUE TITLE
Running more than one instance of IBController on the same machine does not appear to work

### ISSUE THREAD

**Issue by bhahn1800** [ib-controller/ib-controller#168]
I'm trying to run 2 instances of IBController on the same Win10 PC.  I can only run 1 instance at a time it seems... both accounts work but only if you have one running.  There does not seem to be anything meaningful produced in the log file.  I have also tried to make sure that the IbControllerPort is different in both configurations. 

In prior versions of IBController from years ago, I was able to do this.

**Comment by shevkoplyas** [comment]
before trying to run 2 instances of IBControllers you need to be able to
manually run 2 TWS instances on same PC at the same time side by side.
You mentioned "both accounts work, but only if you have one running", which
suggests me you're not using "offline version" of TWS, which is the must.

cheers,
Dmitry

**Comment by rlktradewright** [comment]
You need to make sure you're using different log file directories for the two instances.

**Comment by rlktradewright** [comment]
Oops, didn't mean to close this: one of the silly 'design' features in Github - it's much too easy to click 'Close and comment' instead of just 'Comment'.

**Comment by bhahn1800** [comment]
Dmitry - thanks for your reply... both accounts can run simultaneously using the standalone TWS application.

Richard - I will try setting the log file directories differently to see if that can give me a message that can provide more insight.  thanks

**Comment by bhahn1800** [comment]
I just set the log directories to be different, and I can now run them both at the same time... thanks for the help
