### ISSUE TITLE
New to IBController - Error in log file "TWS version 968 is not installed"

### ISSUE THREAD

**Issue by jserper** [ib-controller/ib-controller#170]
Hello,

I'm just starting with IBController. I went into TWS help/about and the build is 968.2f. I went into the IBControllerStart.bat file and edited the version line to read: 

set TWS_MAJOR_VRSN=968

Saved the file. Then when I ran the batch file it did not work (turned red).  I received the following error msg in the IBController log file:

Error: TWS version 968 is not installed

I'm new so I must be doing something wrong. Please assist. Thanks.

Jon

**Comment by rlktradewright** [comment]
Well actually, you only quoted the first part of the error message. The full message says:
```
TWS version 968 is not installed
You must install the offline version of TWS/Gateway
IBController does not work with the auto-updating TWS/Gateway
```
and that tells you exactly what's wrong.

**Comment by jserper** [comment]
Thanks Richard. Fyi - the rest of the error message does not show up in my log file.

 

Just so I understand – the offline version of TWS is the version that IBController uses to establish an online connection?

**Comment by rlktradewright** [comment]
The message I quoted is the current version, which was released on July 17 2017 (IBController v3.4.0). If you're just starting with IBController, why aren't you using the latest version?


To understand what I mean by the offline version, I suggest you read the User Guide. I don't see any reason why I should explain it all over again.

Sorry if I sound grumpy about this, but my time is valuable and there's absolutely no reason why you should have made this error. And having made it, you could easily have found the many previous issues where this same question has been answered, and it's ALWAYS for the same reason (which is primarily that people don't RTFM).

**Comment by jserper** [comment]
Hello,

 

I do not take lightly to the attitude you are conveying below – it stinks. I’m sure you do this a lot and have heard it before. 

 

There are a lot of versions floating out there and I’m new to this. Believe me I’ll catch on quickly and within a week you won’t see any dumb questions from me. However if you cannot take a minute to be nice & answer one or two up front questions then clam it and don’t answer at all. I’ll just record a macro and run this thing another way.

 

Jon

**Comment by rlktradewright** [comment]
The vast majority of people who start to use IBController download the software from the official repository, read the User Guide, follow the very simple instructions, and it just works. It's really about as easy as it possibly could be.

But there are a few people who pick up a copy that's floating around somewhere, don't read the instructions, fiddle around with a bit of it to try it out, fail to make it work, and then get narky when it's suggested to them that their strategy is non-optimal.

Sadly, you appear to be one of the latter...
