### ISSUE TITLE
xterm: Xt error: Can't open display: xterm: DISPLAY is not set

### ISSUE THREAD

**Issue by karunkrishna** [ib-controller/ib-controller#172]
Trying to run this on Ubuntu on aws for automation 
(4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

I have followed the direction mentioned in the user guide regarding Default Folder and downloading TWS API (Offline) Standalone client and updating the runscript to use the correct version 968 

When I run the ./IBControllerStart.sh  or ./IBControllerGatewayStart.sh

I get the following output:
ubuntu@ip-172-xx-xx-xxx:/opt/IBController$ xterm: Xt error: Can't open display:
xterm: DISPLAY is not set

To Note:

ubuntu@ip-172-xx-xx-xxx:/opt/IBController$ grep -i x11 /etc/ssh/sshd_config
X11Forwarding yes
X11DisplayOffset 10

ubuntu@ip-172-xx-xx-xxx:/opt/IBController$ echo $DISPLAY
:0

Not sure what to do here...

**Comment by shevkoplyas** [comment]
this might help:
How to setup IBController (3.4.0) + TWS (build 967.1e) on headless Ubuntu
16.04 LTS to run TWO accounts (paper + real) in 10 minutes
<https://dimon.ca/how-to-setup-ibcontroller-and-tws-on-headless-ubuntu-in-10-minutes/>

**Comment by karunkrishna** [comment]
Thanks! Got me future. I put in Dispaly=:0 before the runscript. 

I got the following exception though. Not sure if I need to put in a java path...didn't think I had to based on instructions...I could have missed it. 

================================================================================

Starting IBController version 3.4.0 on 2017-12-25 at 01:26:51

Operating system: Linux ip-172-31-44-131 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Arguments:

TWS version = 968
Entry point = ibcontroller.IBController
--tws-path = /home/ubuntu/Jts
--tws-settings-path = /home/ubuntu/Jts
--ibc-path = /opt/IBController
--ibc-ini = /home/ubuntu/IBController/IBController.ini
--mode =
--java-path =
--user =
--pw =

=================================
Generating the classpath
Classpath=/home/ubuntu/Jts/968/jars/jts4launch-968.jar:/home/ubuntu/Jts/968/jars/locales.jar:/home/ubuntu/Jts/968/jars/log4j-api-2.5.jar:/home/ubuntu/Jts/968/jars/log4j-core-2.5.jar:/home/ubuntu/Jts/968/jars/total-2017.jar:/home/ubuntu/Jts/968/jars/twslaunch-968.jar:/home/ubuntu/Jts/968/jars/twslaunch-install4j-1.8.jar:/opt/IBController/IBController.jar

Generating the JAVA VM options
Java VM Options=^M -Xmx768m^M ^M ^M

Determining the location of java executable
Could not find c:program filescommon filesi4j_jres1.8.0_152^M/bin/java

=========================== An error has occurred =============================



Error: Can\'t find suitable Java installation

**Comment by karunkrishna** [comment]
Closing. Upcaked the wrong tws version.

**Comment by dhgclt** [comment]
https://github.com/dhgclt/xterm-fix-for-kali-nethunter/blob/main/README.md
