### ISSUE TITLE
TWS Standalone Headless installation stopped working

### ISSUE THREAD

**Issue by rickygu** [ib-controller/ib-controller#186]
So I've been running TWS Standalone (total.2013.jar) for 2 years on a headless ubuntu server and today it stopped working due to deprecation of my TWS version.

My TWS can no longer connect and gave the following error:

BX 04:05:28:144 JTS-LogonDispatcherS1-20: LogonDispatcher received reject(probably running an old ccp version), reason [<html>The version of the application you are running, 952.1e, is no longer supported.<br>
Please download the current version <a href="https://www.interactivebrokers.com/en/p.php?f=tws&p=software&ib_entity=llc">from our web site</a>.</html>]^M

I'm running a standalone version of TWS standalone downloaded from here
[https://www.interactivebrokers.com/en/index.php?f=5068)](url)

It doesn't seem like they have updated this page with a newer TWS standalone version. 

with this gist script so it can be run in a headless mode on a cloud server.
[https://gist.github.com/rickygu/c50f6220c769dbbe734e3e007cd0d35e](url)

I looked around and I can't find any updated version of TWS standalone that gives me the .jar file to do a drop in replacement of my setup. Anyone know what's best way to fix this problem and get TWS running on my headless server?

**Comment by acuariano** [comment]
Having similar problems. Found any solution?

**Comment by rickygu** [comment]
I've been trying to do a brand new setup following this more updated instruction here [https://dimon.ca/how-to-setup-ibcontroller-and-tws-on-headless-ubuntu-in-10-minutes/](url)

How ever it's taking a long time because I've been getting stuck at various parts. 

right now I'm stuck on starting TWS with IBController. The log would show:

> 07:09:24:647 IBController: detected frame entitled: Login; event=Activated
07:09:24:658 IBController: detected frame entitled: Login; event=Opened
07:09:24:661 IBController: trading mode from settings: tradingMode=live
07:09:24:661 IBController: Setting Trading mode = live
07:09:24:682 IBController: s3Store=true
07:09:24:867 IBController: Click button: Login
07:09:25:187 IBController: Button now disabled: Login
07:09:25:951 IBController: detected frame entitled: Authenticating...; event=Activated
07:09:25:954 IBController: detected frame entitled: Authenticating...; event=Opened

then it would be stuck and TWS won't open.

**Comment by rickygu** [comment]
Update: Managed to get TWS to open. The instruction above has PasswordEncrypted=yes and I didn't encrypt the password so it wasn't logging in. After i changed it to no it finally launched.
