### ISSUE TITLE
ERROR Attempted to append to non-started appender

### ISSUE THREAD

**Issue by TRVDE** [ib-controller/ib-controller#192]
The latest version of IBController doesn't seem to work with the latest version of TWS (971).
After starting IBControllerStart.bat the batchfile windows turn to red and refer to the log file.
The log says: JTS-IA-Usage-Reporter-1 ERROR Attempted to append to non-started appender d
Starting TWS manually works fine.
Any ideas?
Regards
Tom

**Comment by rlktradewright** [comment]
Actually it works perfectly.

If you want help, I suggest you read this, and act accordingly:


[https://groups.io/g/ibcalpha/message/570](https://groups.io/g/ibcalpha/message/570)

**Comment by TRVDE** [comment]
Thanks. I started using IBCWin now. I'm using it in conjunction with "AlwaysUp". This has been working fine over the last couple of years but since the update AlwaysUp doesn't notice IBC is started. I think this is a problem I should discuss with the support of AlwaysUp.

**Comment by rlktradewright** [comment]
If you want to continue this discussion, please close this issue and open a new one on the IBC Github site. Thanks.
