### ISSUE TITLE
How to AutoClose IBController everyday?

### ISSUE THREAD

**Issue by memoryfraction** [ib-controller/ib-controller#193]
I found process java.exe (IBController.jar) becomes a dead process(exist but doesn't work) in some  random interval, e.g. every 1-3 days.
So, I want to close it every evening, so that, windows scheduler can restart the instance

I tried "IBControllerStop.bat" by double click it manually; However, telnet screen appears and lasts about 2 seconds, then it disappears.  Nothing changed. 
Anything wrong I did? Why it doesn't work?

OS is windows server 2008 R2 Standard Service Pack 1 - 64 bit

File is also attached;
[IBControllerStop.zip](https://github.com/ib-controller/ib-controller/files/2037667/IBControllerStop.zip)

Appreciate any advice and help

**Comment by rlktradewright** [comment]
Read this:

[https://groups.io/g/ibcalpha/message/570](https://groups.io/g/ibcalpha/message/570)

and this:

[https://github.com/IbcAlpha/IBC](https://github.com/IbcAlpha/IBC)

**Comment by memoryfraction** [comment]
I downloaded the latest version 3.6.0 for windows from https://github.com/IbcAlpha/IBC/releases/tag/3.6.0
The same phenomenon still exist, I mean, when I double click "Stop.bat", telnet screen appears and lasts for about 2 seconds, then it disappears with TWS still running.

Any comments?

Thanks

**Comment by memoryfraction** [comment]
I did a video for what happens in my computer.
File attached;
[kk 2018-05-25 16-36-46.zip](https://github.com/ib-controller/ib-controller/files/2040796/kk.2018-05-25.16-36-46.zip)

**Comment by rlktradewright** [comment]
Please close this issue and re-raise it on the IBC repository.
