### ISSUE TITLE
AcceptIncomingConnectionAction=accept does not seem to work with an IB Gateway

### ISSUE THREAD

**Issue by sandrinr** [ib-controller/ib-controller#197]
This might not be strictly a IBC issue.

The IBC connection auto accept `AcceptIncomingConnectionAction` does not seem to work for me (neither with gateway 963 nor 972).
My IB Gateway does not seem to ask when someone tries to connect from an untrusted IP address (with non localhost traffic enabled). When I try to connect from another host (e.g. using the TestClient), the connection is closed short after the connection is established.

I am trying this inside a Docker environment where it might be difficult to configure the list of trusted IP addresses in front of all containers running.

Anyone also experiencing this?

**Comment by rlktradewright** [comment]
This is the defunct IBController repository, not IBC.

Please post in the right place!

**Comment by sandrinr** [comment]
Oh, my bad!
