### ISSUE TITLE
IB Controller doesn't work with new version of IB Gateway/TWS (974.4a)

### ISSUE THREAD

**Issue by nobel1101** [ib-controller/ib-controller#209]
IB has just released a new version of TWS/IB Gateway. I've changed the IBControllerGatewayStart.bat and the IBControllerStart.bat files to version 974 accordingly.
However the new version of both IB Gateway and TWS present a new login screen, with username and password not filled in.
I have to manually fill in the login details before proceeding.

(Note: I was originally using version 973)
![image](https://user-images.githubusercontent.com/44996331/48399556-dea09800-e71b-11e8-8ac6-5c5b35bfe802.png)

**Comment by DMTSource** [comment]
https://github.com/ib-controller/ib-controller/issues/207 contains an explanation & fix via new IBC repository, for those who need things working asap. 

I was also able temporarily avoid the issue via a roll back to the last 'stable version', tws 972 offline, but this last-stable version could change at any time on the download page.

**Comment by nobel1101** [comment]
I can confirm the latest version of IBC has fixed the problem

**Comment by lihanchen** [comment]
Which version is that?
I am using the latest release 3.4.0 and it doesn't work for 974.
Should I try the latest source code?

**Comment by nobel1101** [comment]
974 won't work with IBController. Only IBC (a sister application of IBController) supports TWS/IBGateway 974. (https://github.com/IbcAlpha/IBC)
