### ISSUE TITLE
Error when runing IBControllerStart.sh

### ISSUE THREAD

**Issue by teuffy** [ib-controller/ib-controller#21]
Hi 
I have some difficulties to get it running. got this error message?

Error: Could not find or load main class ibcontroller.IBController

**Comment by rlktradewright** [comment]
This means that when the java command is issued, the IBCDIR variable is not pointing to the directory that contains IBController.jar. Since that variable is set a few lines higher up in the .sh file, it should be easy enough for you to work out what's wrong. If you can't, then you'll have to supply more information, eg the contents of your IBControllerStart.sh file.

**Comment by teuffy** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Thanks Richard
It was installed in IBController/IBControler --> fixed
Now I have this erro (running it on ubuntu server headless

15:21:55:492 AWT-EventQueue-0: Error
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an
operation which requires it.
	at
java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:218)
	at twslaunch.jclient.ad.<init>(ad.java:441)
	at twslaunch.jclient.bd.<init>(bd.java:482)
	at jclient.rr.run(rr.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomai
n.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
	at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.
java:242)
	at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.jav
a:161)
	at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.
java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146
)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138
)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)


On 25/03/15 15:15, Richard L King wrote:
> This means that when the java command is issued, the IBCDIR
> variable is not pointing to the directory that contains
> IBController.jar. Since that variable is set a few lines higher up
> in the .sh file, it should be easy enough for you to work out
> what's wrong. If you can't, then you'll have to supply more
> information, eg the contents of your IBControllerStart.sh file.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/ib-controller/ib-controller/issues/21#issuecomment
- -86045822>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: GPGTools - https://gpgtools.org

iQEcBAEBCgAGBQJVEsVYAAoJECbGaFMxFA5h1loH/3IWBxNUNqKyl86T9vn+cGEt
/Pc/Gxxzl9uvScuYG2kCLEhHcdezFmCFIODawOy1BI+0QLtjuww5sigjMhqb+kSQ
GWsf5KmWTTaSSzuh6fBsA7ucrbTkl+lpL0IQyImcOfdNSjOjymXXP1twftciLNeX
Y2NqJl+Sym/WfDnriN0GyALyGWVdh1FdG30+tz1xX0VR/7kAI+3rBYnGvUr9U2kI
MM2PzsyNu3bM3fNj8rdjgYt6Pr04GbxvGr20BeEeZdm9t1Oa51gDZ3gbDkeTAt/m
DDZqnxk9aJvi1W1myylqJeWl4RmRYcUrrNes8j3SeT7xs3E3JWbbYjeIJMdImwQ=
=7kRt
-----END PGP SIGNATURE-----

**Comment by rlktradewright** [comment]
Well, this is a matter of knowing how to run GUI programs on a headless server, and is nothing to do with IBController itself.

I'm not a Linux expert, so I can't tell you how to approach this. My advice would be to do some searching or post a question on the Ubuntu forums.

I now consider this issue closed.

**Comment by benalexau** [comment]
@teuffy , see https://github.com/benalexau/ibcontroller-aur/blob/master/package/ibcontroller%40.service for a systemd startup file that uses virtual framebuffers to launch IBController.
