### ISSUE TITLE
Not working with TWS version 949.3d (latest)?

### ISSUE THREAD

**Issue by ibiza240** [ib-controller/ib-controller#24]
Hi,

I managed to make the controller work until I get this window :

![Error](http://i.imgur.com/zQLyrI8.png)

It looks like the error is because of a newer version of TWS than the one supported..?

Thanks for your great contribution

**Comment by rlktradewright** [comment]
I just installed that version and it works with no problems.

The error message you posted is actually very misleading: the words are from a version of TWS years ago, and they did actually mean something then, but nowadays it would be much more accurate to say that total.2012.jar is missing from the classpath (assuming that the message still bears any relation to its original meaning).

This indicates that there's something wrong in your IBControllerStart.bat file. Please make sure that the lines beginning

set TWSDIR=

and 

set TWSCP=

are correct. If you're not sure, post the contents of IBControllerStart.bat here.

**Comment by ibiza240** [comment]
Thanks! 

With your feedback, I will test more tonight and come back here this evening with my findings (and my .bat file content if needed)

One thing I am thinking off the top of my head is that I specified total.2015.jar and not 2012 in my bat file, maybe it is that.

Best regards

**Comment by rlktradewright** [comment]
Yes, that would certainly explain it.

But I don't understand why you would make such a change. Is there something in the User Guide that made you think this was necessary?

**Comment by ibiza240** [comment]
Hi,

I tested very briefly yesterday evening (did not have as much free time as I thought) and it worked if I put in the bat file :+1: 

set TWSDIR=[MyTWSDirectory]
and
set TWSDIR=jts.jar;total.2012.jar

Thanks! :)

**Comment by rlktradewright** [comment]
Closed/
