### ISSUE TITLE
Set trusted IP

### ISSUE THREAD

**Issue by creack** [ib-controller/ib-controller#28]
Hello,

Is there a way to set the trusted IP? I'd like to run remotely and by default, only 127.0.0.1 is accepted.

**Comment by rlktradewright** [comment]
You set the trusted IP addresses via TWS's API configuration dialog. Nothing to do with IBController.

**Comment by creack** [comment]
Not sure to follow. In order to do that, I need to run the full blown TWS thingy? i.e. install Xorg & co?

**Comment by rlktradewright** [comment]
Well, you don't need to run TWS, you can run the gateway instead. But that still has a user interface via which you can configure the trusted address(es).

IBController assumes that you have a valid working TWS installation, configured as you need it (with the exception that it will configure the API port number if you request it to).

Note that you don't have to set the trusted IP address(es). You can tell IBController to handle the 'Accept incoming connection' dialog: see the description for the AcceptIncomingConnectionAction setting in the .ini file. However, setting trusted IP addresses is much more secure, especially if TWS is running on a host outside your network.

Note also that you could do the TWS configuration on a local machine, then copy the installation over to your target machine.

I'm not sufficiently Linux-savyy to advise you on running TWS/Gateway headless, but perhaps @benalexau may have something to add here.

What I would say is that you need to be very certain that you're comfortable with not having easy access to the TWS user interface. It's a useful backstop in case, for example, you need to closeout all your positions manually.

**Comment by creack** [comment]
For the moment, I am running a socat that proxies any incoming connection to the IB. I'll take a look at AcceptIncomingConnectionAction, thanks :).

For the interface, I can shutdown the remote one and start a "regular" TWS fast enough.

**Comment by Foreverflying** [comment]
i don't know why, when i tried IBGateway version 963 and 965 on linux, if i connect the gateway from a non trusted ip address, it doesn't pop a dialog as the introduction told me, instead, the connection just shutdown at once, even without any log info.
so i have to add the trust ip manually, then everything goes well.

another question is:
after i add the trust ip and shutdown the IBGateway, i think the trust ip list has been saved somewhere, for it remains when i start the gateway again.
and also i'm sure it saved locally, for if i start the gateway on another environment, the list isn't updated.
but i didn't see it in the jts.ini file, this confuses me a lot.

**Comment by Foreverflying** [comment]
ok, i've find the answer from you from this link:
https://www.bountysource.com/issues/30506593-setting-for-overriding-the-localhost-only-option

any how, this makes it hard to use in docker, for while using docker container, it's nearly impossible to connect the ibgateway from localhost.
let me find a workaround...

**Comment by Foreverflying** [comment]
i am a layman on linux X programs.
maybe the "system-generated pop up message" can not be seen from my XWindow server, for i didn't run a desktop environment?

i get an idea: to use a ssh tunnel, may be a preferable solution in docker.

**Comment by rlktradewright** [comment]
@Foreverflying 

Why have you tried to resurrect this issue which was closed TWO YEARSAGO??

You should create a new one that addresses your specific problem, not hijack someone else's.

**Comment by Foreverflying** [comment]
@rlktradewright 
oops... i googled to this page and didn't notice the post date.
sorry

**Comment by tomer-ds** [comment]
@foreverflying did you ever open a new issue?
