### ISSUE TITLE
IBGateway Server Not Starting For Live Trading user.

### ISSUE THREAD

**Issue by ngyangjo** [ib-controller/ib-controller#34]
Hi,
I'm getting following message while trying to run IBControllerGatewayStart.sh and IBController does start listening but IBGateway server does not start up. 
JTS-Fuse-sd-63: Reset transferrable socket:ushmds cdc1.ibllc.com:4000

Can anyone tell me what's the exact issue and how do i get over it?

However, everything works fine when i use demo user. But using my secondary user of the live trading account tend to cause the above issue. The security card login is disabled for secondary user. And im using IBGatway version: 939.5c and IBController 2.13.1

**Comment by rlktradewright** [comment]
I recall that 939.5c no longer supports API connections. You need to be using 9.40 or later for API access - there is a prominent notice to this effect on IB's website.

So install a later version and try again.

**Comment by ngyangjo** [comment]
Can you provide me the place from where i can download 9.4 version of IBGateway. I'm trying to get rid of the "Read only API" settings which they have introduced in new version.

**Comment by rlktradewright** [comment]
There's no way to download versions from 940 to 949 from IB's website, which is stupid of them, especially given that there seem to be bugs in maintaining the correct setting for 'Read only API' in the latest version.

However here's a link to TWS 944 on my OneDrive.. I keep older versions of TWS until I'm absolutely sure I'm not gong to need them. 944 is the version I currently use for live work.

https://onedrive.live.com/redir?resid=599F0C96432C9F5A!77115&authkey=!AJsG4ddhzH_M7Uk&ithint=file%2cexe

**Comment by ngyangjo** [comment]
Thank you very much. But the link is provided contains a .exe file. Do you happen to have a .jar file too?

**Comment by rlktradewright** [comment]
Well, the exe file is the install file exactly as provided by IB, and I guarantee that it hasn't been tampered with.

However if you're concerned, yes I can provide the jar file, just give me a few minutes to get it off the machine it's on and into my OneDrive.

I'll let you know when it's ready.

**Comment by ngyangjo** [comment]
Thanks a ton. You are a life saver.

**Comment by rlktradewright** [comment]
https://onedrive.live.com/redir?resid=599F0C96432C9F5A!77124&authkey=!AA-OugiH6NWTsoI&ithint=file%2cjar

**Comment by ngyangjo** [comment]
Hi,
I extracted your jar but i couldn't find the folder that contains the ibgateway jars such as jts.jar, total.2013.jar, locales.jar. And also there seems to be a lot of folders and files, are they from interactive brokers?or are they your custom classes and folders.

**Comment by rlktradewright** [comment]
The file I provided *is* jts.jar. I thought that's what you were asking for.

There's no need to extract anything, just copy it over the jts.jar in your TWS installation folder and away you go. All the other jar files that come in the TWS installer are exactly the same between the two versions, so there's no reason for me to provide them.

Oh, maybe you're running on Linux and it's the unixmacosx.jar (or whatever it's called) file that you want? In that case, you're out of luck - I don't keep them.

**Comment by ngyangjo** [comment]
Well it almost worked. I replaced the jts.jar with the one you provided and server started successfully, but while making API call i got, "Enable ActiveX..." error.

**Comment by rlktradewright** [comment]
Ok, so can I assume you are running on Windows? It would be helpful to know, because I believe the Windows jars are not the same as the Unix jars (even though you'd think they ought to be, since it's written in Java and hence potentially cross-platform).

As far as I can see, you only have two options:

1. If you think you need more than just the jar I sent you, then you should uninstall TWS and use the first file I uploaded to reinstall it. You have my personal cast-iron guarantee that this is exactly the same installer that you could have downloaded some time ago from IB's website.

2. Otherwise, you have to find a way to go into the API configuration in TWS/Gateway and make sure you have the right settings. 

I note that in your post on the TWSAPI forum (I presume that was you?) you said you were running headless: if you are running so headless that you have no way to show the TWS/Gateway GUI, then I'd say you're just asking for trouble.

**Comment by ngyangjo** [comment]
No, I'm not running in windows and yes that was me in the Yahoo TWS API forum. 
I'm trying to run IBGateway in my linux server that does not have any GUI. Everything would have worked just fine, only if IB would not have introduced the "Read Only API" setting.
Anyways, thanks for your time and effort, highly appreciated it. I'll look some more, if i can find another solution.
