### ISSUE TITLE
What are possible values of IBBindAddress?

### ISSUE THREAD

**Issue by ngyangjo** [ib-controller/ib-controller#35]
I am running IBGateway in a server whose ip is x.x.x.x and i'm trying to connect to this IBGateway from another server y.y.y.y. In IBBindAdress, i tried putting y.y.y.y but it gives me following exception:

13:55:07:804 IBController: exception:
java.net.BindException: Cannot assign requested address

Does this parameter only takes 127.0.0.1? Is there any way i can achieve the above thing?

**Comment by rlktradewright** [comment]
The description of the section in the .ini file that contains IbBindAddress includes the following statement:

# Do NOT CHANGE THE FOLLOWING SETTINGS unless you
# intend to issue commands to IBController (for example
# using telnet). Note that these settings have nothing to
# do with running programs that use the TWS API.

Since you are trying to connect to the TWS API, your question is clearly inappropriate.

You don't specify the address of the machine you want to connect to via IBController: you do it in the connect call in your API code.

**Comment by ngyangjo** [comment]
I've provided the IP of the machine in the API code and i'm getting "Enable ActiveX" error message. So i think we should also specify the IP address of the machine that's trying to connect i.e. the client machine. IBGateway API Setting has something called Trusted IP Address but since i'm in a linux server that does not have any UI, I am looking for the parameter in the IBController.

**Comment by rlktradewright** [comment]
It is not IBController's function to configure the TWS API. That is your responsibility. How you do it is up to you. Here are some options:

1. Install a means of accessing the Gateway user interface on your target machine. For example use xvfb and x11vnc (see https://en.wikipedia.org/wiki/Xvfb). I recommend you do this - the fact is that both TWS and the Gateway are GUI programs (and if they weren't IBController wouldn't work), and not having access to that GUI will almost certainly cause you problems at some point (it already is!).

2. Install and configure TWS/Gateway on a machine to which you do have access, then copy the whole thing over to your target machine (actually you probably only need to copy over the settings file: the settings are held in a file called something like gateway.xml (and/or gateway.<day>.xml) in a subfolder of your TWS installation folder with a funny name like djkknie).

3. Edit the TWS settings file directly. I don't recommend this, and if you want to try it, you're on your own! .

Note that IBController has an ENABLEAPI command that you can send via telnet, but you can't use this to configure the Trusted IP Addresses.
