### ISSUE TITLE
add "log in as a client" dialog handler

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [ib-controller/ib-controller#37]
![image](https://cloud.githubusercontent.com/assets/1622151/9016264/3579567e-3795-11e5-9168-fe03a60840a2.png)

```
package ibcontroller;

import java.awt.Window;
import java.awt.event.WindowEvent;

import javax.swing.JDialog;

class LoginAsClientDialogHandler implements WindowHandler {

	static final String LABEL = "log in as a client";

	public boolean filterEvent(Window window, int eventId) {
		switch (eventId) {
		case WindowEvent.WINDOW_OPENED:
		case WindowEvent.WINDOW_ACTIVATED:
			return true;
		default:
			return false;
		}
	}

	public void handleWindow(Window window, int eventID) {
		if (Utils.clickButton(window, "Close")) {
			Utils.logToConsole("dismissed " + LABEL + " dialog");
		} else {
			Utils.logError("could not dismiss " + LABEL + " dialog");
		}
	}

	public boolean recogniseWindow(Window window) {
		if (!(window instanceof JDialog))
			return false;

		if (Utils.findLabel(window, LABEL) != null)
			return true;

		return false;
	}

}
```

**Comment by rlktradewright** [comment]
Given that this window only appears when the TWS demo system is in use, and that it's completely trivial to close manually, I see no reason to include this change in IBController.

If you're starting TWS so often that this gets irritating, it's probably time to actually open an account with IB! After all, the demo system is practically useless for anything except the most trivial testing. It's really not safe to assume that it behaves in the same way as the live or paper-trading account.

**Comment by Andrei-Pozolotin** [comment]
I use demo account for integration tests.
OK, I will keep my own fork.
