### ISSUE TITLE
option to set the color palett/skin

### ISSUE THREAD

**Issue by aggarwalmanuj** [ib-controller/ib-controller#38]
is there a way to specify which color palette/skin to launch TWS with (dark/light etc.)?

thanks

**Comment by rlktradewright** [comment]
You can't set this via IBController. You need to set it manually by logging into TWS without using IBController. You only need to do it once, so it's not a big inconvenience.

It is not IBController's purpose to provide a means of automatically configuring aspects of TWS that can be configured manually.

**Comment by aggarwalmanuj** [comment]
Understood. But if one needs to run several instances of TWS on single machine (one instance per account) - then TWS loses that setting. And AFAIK there is no way to set it once we have logged into TWS.

**Comment by rlktradewright** [comment]
I run two instances of TWS all the time, and their settings are entirely independent. I can change the look and feel or anything else about the configuration of one instance without affecting the other in any way. So I don't understand your claim. 

In fact not only do my two instances of TWS have their own settings, they're actually two different versions of TWS: one of them is my live account, and I rarely update this version of TWS, whereas the other is my paper trading account and that runs on a more recent version (often the latest, just to see what IB have done to it, to make sure it still works with IBController, etc).

Maybe it hasn't occurred to you that to do this, you need to have a separate directory for each TWS instance, containing all the TWS code. So just copy your C:\Jts folder (or whatever) into C:\JtsA, C:\JtsB,.. etc. You'll need to also set up different IBController scripts for each one. It's really pretty straightforward.

**Comment by aggarwalmanuj** [comment]
Well sometimes it is not possible due to some other dependencies or programs which are connecting to TWS. Anyway thank for your help.
