### ISSUE TITLE
IBController not preventing autologoff on 952.1a

### ISSUE THREAD

**Issue by Denebulas** [ib-controller/ib-controller#41]
running english TWS  952.1a via IBController 2.14 on a XP virtual machine.
I set the autologoff time 30 sec ahead and TWS happily logoff without messages...
this is the log:

ialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=4749666
06:53:45:630 JTS-cashfarmDispatcherS6-101:  NS_AUTH_START version=7 pwd=0 soft=2 token=0 tokenSubtype=0 init
ialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=29968752
06:53:51:989 JTS-usfarmDispatcherS7-110:  NS_AUTH_START version=7 pwd=0 soft=2 token=0 tokenSubtype=0 initia
lTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=15176952
06:53:51:999 JTS-ushmdsDispatcherS8-114:  NS_AUTH_START version=7 pwd=0 soft=2 token=0 tokenSubtype=0 initia
lTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=28743942
06:55:45:382 AWT-EventQueue-0: <html>Trader Workstation<br>Copyright ? 2000 LICENSOR to Interactive Brokers<
br>ALL RIGHTS RESERVED<br><br>Build 952.1a, Aug 18, 2015 3:38:07 PM<br>Jolt Build 1.3.0, Jul 31, 2015 04:11:
05 PM<br>Nia Build 2.4.3, Aug 7, 2015 02:26:49 PM<br>ModelNav Build 1.4.3, Jul 28, 2015 02:33:29 PM<br>Riskf
eed Build 2.7.1, Aug 10, 2015 09:11:37 AM<br><br>Java Version: 1.8.0_60, OS: Windows XP (x86, 5.1), Memory:
heap <br>max 989Mb, current 138Mb<br><br>This software is covered by U.S. Patent No. 7.827.092.<br><br>This
software uses JFreeChart class library from<br>Object Refinery Limited under the terms of the GNU<br>Lesser
General Public Licence, which can be found here:<br>http://www.object-refinery.com/lgpl.html.<br><br>This pr
oduct includes software developed by the JDOM<br>(http://www.jdom.org/) and ROME (http://rome.dev.java.net)<
br>projects.<br><br>This software includes software developed by Hypersonic<br>SQL Group under its licence w
hich can be found here<br>http://hsqldb.org/web/hsqlLicense.html.<br><br>This product includes unmodified so
ftware developed by<br>Pentaho Corporation (Mondrian 3.9.0.0-213) under its license<br>that can be found at
http://www.pentaho.com/license.<br><br>This product uses the "Secure Remote Password" cryptographic<br>authe
ntication system developed by Tom Wu (tjw@CS.Stanford.EDU).<br><br>This software includes unmodified Apache
HttpComponents class library from<br>Apache Software Foundation under the terms of Apache License,<br>which
can be found here: http://www.apache.org/licenses/LICENSE-2.0<br><br>This software includes unmodified Apach
e Commons Logging class library from<br>Apache Software Foundation under the terms of Apache License,<br>whi
ch can be found here: http://www.apache.org/licenses/LICENSE-2.0<br><br>This software uses JSON reference im
plementation under JSON license,<br>which can be found at http://www.json.org/license.html<br><br><a href='h
ttps://www.interactivebrokers.com'>Interactive Brokers Home Page</a></html>
06:56:07:114 JTS-CommonScheduler-57: Disconnecting usfarm.us when checking activity
06:56:22:596 JTS-ActivityBus-27: Terminating async queue thread
06:56:22:596 JTS-RecordNotifier-30: Terminating async queue thread
06:56:22:596 JTS-AsyncNonLocked-26: Terminating async queue thread
06:56:22:646 JTS-Async-25: Terminating async queue thread
06:56:23:077 JTS-EServerSocket-61: [99:51:76:1:0:0:0:ERR] Socket connection for client{99} has closed.
06:56:23:097 JTS-EServerSocket-72: [23140:45:76:1:0:0:0:ERR] Socket connection for client{23140} has closed.

06:56:23:097 JTS-EServerSocketNotifier-73: Terminating async queue thread
06:56:23:097 JTS-EServerSocketNotifier-62: Terminating async queue thread
06:56:24:152 JTS-onReceiveUploadSignature-141: S3: Starting tws.wlist settings upload
06:56:24:362 JTS-onReceiveUploadSignature-141: S3: Uploaded settings : 300 1049
06:56:28:868 JTS-onReceiveUploadSignature-145: S3: Starting tws.xml settings upload
06:56:30:330 JTS-ShutdownTask-Uploading_Settings-144: Waiting upload timeout failed
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at jclient.login.u.j(u.java:614)
        at jclient.login.kb.b(kb.java:511)
        at jclient.login.jb.run(jb.java:174)
        at java.lang.Thread.run(Unknown Source)
06:56:31:192 JTS-ExecNotifier-32: Terminating async queue thread
06:56:31:272 JTS-Order-Audit-17: Terminating async queue thread

C:\Jts>popd

**Comment by rlktradewright** [comment]
Five minutes before TWS auto-logs-off, it displays a dialog warning of the impending auto-logoff. When this dialog appears, IBController intercepts it and clicks the relevant button to prevent the auto-logoff.

If you set the autologoff time only 30 seconds in the future, TWS doesn't display this dialog (presumably it thinks there's no point giving a 5-minute warning for something that's gong to happen in 30 seconds. So IBController can't take any action to prevent auto-logoff.

There is no other way for IBController to know when auto-logoff will occur.

So try being a little bit patient and set the autologoff time more than 5 minutes in the future!

**Comment by Denebulas** [comment]
Thank you I was expecting something stupid like this and not a bug !
