### ISSUE TITLE
IBController - login from real money account

### ISSUE THREAD

**Issue by bobgit3** [ib-controller/ib-controller#48]
From IBController.ini:

" # If ReadOnlyLogin is set to 'yes', and the user is enrolled in IB's
# account security programme, the user will not be asked to supply 
# the security code, and login to TWS will occur automatically in 
# read-only mode: in this mode, placing or managing orders is not 
# allowed. If set to 'no', and the user is enrolled in IB's account
# security programme, the user must supply the relevant security
# code to complete the login. If the user is not enrolled in IB's
# account security programme, this setting is ignored. The default
# is 'no'.

ReadOnlyLogin=no"

I have IBController working on demo account, but as I read this it will not be possible to use Windows Scheduler to automatically open TWS and trade (via an API connection between TradingBlox and Interactive Brokers) on a real money account.

If ReadOnlyLogin is set to yes and user is enrolled in IB's account security programme (I am, don't think there was a choice) you are logged into read-only mode.  If ReadOnlyLogin is set to no, I would have to manually enter the 2 codes corresponding to the different number sets displayed each time I log in.

Hopefully I have misunderstood this or there is a workaround.

Hope this is the right place to post this.

Thanks very much,

Bob

**Comment by rlktradewright** [comment]
You're right, IBController doesn't support automatic non-read-only login if you're enrolled in the security program. But you can opt out of it via Account Management, or you can set up a second user that can login to TWS without the card but can't login to Account Management - see Issue #25 for more information..

**Comment by bobgit3** [comment]
Hi Richard
Thanks!
Bob

Date: Fri, 13 Nov 2015 03:01:22 -0800
