### ISSUE TITLE
Security code card authentication

### ISSUE THREAD

**Issue by ibizaman** [ib-controller/ib-controller#5]
Do you know how to handle Security code card authentication?

```
Jun 24 19:36:17 me xvfb-run[625]: 19:36:17:654 IBController: detected dialog entitled: Security Code Card Authentication; event=Opened
Jun 24 19:36:17 me xvfb-run[625]: 19:36:17:730 IBController: detected dialog entitled: Security Code Card Authentication; event=Activated
```

**Comment by lolero** [comment]
benalexau, thanks for the tip but I cant find the way to disable the password tokens for trading system access.  Can you please point me in the right direction? Thanks!

**Comment by shevkoplyas** [comment]
@lolero, to disable password tokens you'd opt out by logging into IB's
website:
Manage Account -> Security -> Secure login system -> SLS opt out
Then anyone having your login/password will be able to access your trading
account (bad), but you'll be able to completely automate it's start in some
remote headless linux machine in the cloud (good:)

cheers,
Dmitry

On Tue, Feb 9, 2016 at 9:56 AM, lolero <notifications@github.com> wrote:

> benalexau, thanks for the tip but I cant find the way to disable the
> password tokens for trading system access. Can you please point me in the
> right direction? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ib-controller/ib-controller/issues/5#issuecomment-181902248>
> .
>



-- 
с ч.гл.ув.,
Дима Ш.

Dmitry's
<https://docs.google.com/document/d/1gLGdySacvdCrj2XKsf1ufvwxeMjb0LICM7ah05CMefw/pub>
TWS API FAQ <http://goo.gl/TRkeRK>

**Comment by benalexau** [comment]
There is more detail in issue #25, but what you're probably looking for is:

> You can read IB Knowledge Base article, "[Adding a second user for an individual account holder](http://ibkb.interactivebrokers.com/node/1004)" for more information on the process
