### ISSUE TITLE
TWS 954.2a: Sometimes fails to send login information

### ISSUE THREAD

**Issue by ajpierce** [ib-controller/ib-controller#51]
After upgrading to the latest TWS, it would appear that there's some kind of race condition that SOMETIMES (around 20% of the time) logs you in correctly, but most of the time does not.

Here's the console log from a failed login attempt:

```
------------------------------------------------------------
01:50:05:050 IBController: ini file is /opt/IBController/IBController.ini
01:50:05:061 IBController: IBControllerServer is started.
01:50:05:074 IBController: IBControllerServer listening on address: 3054251e0512/172.17.0.2 port: 7462
01:50:05:169 IBController: TWS settings directory is /opt/IBJts/jars 
01:50:05:804 JTS-Main: dayInit: new values: dayOfTheWeek: 1 (Sun), YYYYMMofToday: 201511, YYYYMMDDofToday: 20151129
01:50:05:908 JTS-Main: getFileFromUrl: dest=/opt/IBJts/jars/locales.jar empty sourceSize=61859
01:50:06:970 JTS-Main: Build 954.2a, Oct 30, 2015 4:07:54 PM 
01:50:08:393 AWT-EventQueue-0: Login failed - Failed send NSMsg - java.lang.NullPointerException
```

And here's what TWS looks like:
<img width="483" alt="screen shot 2015-11-28 at 8 54 41 pm" src="https://cloud.githubusercontent.com/assets/64226/11454968/84eed7ac-9612-11e5-98a0-8fc037ef73f6.png">

Something important to note is that if you move the error box, your credentials appear to be correctly entered:
<img width="477" alt="screen shot 2015-11-28 at 8 55 51 pm" src="https://cloud.githubusercontent.com/assets/64226/11454967/811fd806-9612-11e5-93fd-7ed887e7a74a.png">

I've seen this behavior with both demo accounts and personal paper trading accounts.

**Comment by rlktradewright** [comment]
I don't think this is anything to do with IBController. 

As you observe, IBController has correctly filled in the credentials and has presumably clicked the Login button (I assume you've edited out the logfile entries between 01:50:05.970 and 01:50:08.393 which should contain evidence that IBController has indeed clicked the Login button). 

That means that IBController has successfully completed its work, and anything that happens after that (until a dialog is displayed) is out of its control.

I've just started IBController five times with 954.2a running on my paper trading account, and worked faultless every time.

Are you perhaps using it with the demo system?

**Comment by ajpierce** [comment]
Like with #52, this issue is a result of the fact that I was using Docker, and IB was assuming that I was a new user, and the system was behaving in a non-default fashion.  The solution to the problem is detailed in #52.

**Comment by benalexau** [comment]
@ajpierce can you point me at the Dockerfile which installs TWS 954.x? The IB Gateway Dockerfiles I've seen on GitHub install 952.x, being the last version before IB changed the TWS distribution mechanism from unixmacosx.jar to self-extracting shell scripts with a GUI installer.

**Comment by ajpierce** [comment]
@benalexau I've got a working example up on a dev branch; still doing some testing, but I'm not unhappy with it :)

https://github.com/ajpierce/ib_tws_docker/blob/dev/Dockerfile

**Comment by benalexau** [comment]
@rlktradewright my apologies for turning this into a Docker/unattended installer mechanism conversation. However I'm sure others will find this in Google searches and find the details useful though.

@ajpierce, thanks. I see your Dockerfile is piping "n" to the installer, but it didn't work for me. After finding it didn't work, I did some more digging and found IB are using Install4J for these self-extracting installers. In turn http://resources.ej-technologies.com/install4j/help/doc/index.html offers an official unattended installation option and I can confirm `./tws-latest-standalone-linux-x64.sh -q` worked for me.

Another suggestion you might like to consider for the Dockerfile is the [TWS 954 Release Notes](https://www.interactivebrokers.com/en/index.php?f=15912&ns=T#954_api) state both paper trading and production IB API ports are now bound by default. So you may wish to expose both, depending on your intended use case.

I was wondering whether you found a more automated way of overcoming this original issue that does not require copying the XML file from a manually-accepted config path? For example, maybe creating a minimal XML file with the required element/attribute pre-set, or an empty/minimal XML file?

**Comment by rlktradewright** [comment]
@benalexau No problem Ben. It interests me that IBController is being deployed in situations that none of us would have envisaged a few years ago, and I'm all for that. 

I guess one of these days I'll have to start boning up seriously on containers, but frankly at present they're of no value to me personally. I'll probably be quite interested in Windows Server 2016's container facilities when they emerge, being a confirmed Unix hater...

**Comment by ajpierce** [comment]
@benalexau thanks for the info!  Not sure why piping "n" works for me and not for you; maybe it's the linux distro I'm using in my container?  I'll use the magical `-q` instead :+1: 

I agree that passing the whole `tws.xml` file is a less-than-elegant solution, but there are [other issues](https://github.com/pilwon/node-ib/issues/8) that are demanding attention before I can put the finishing touches on the TWS container.  I'll certainly let you know if there's a more compact `tws.xml` I can use; I imagine there's a lot of stuff about the layout and stuff that can be removed, but reading through 3 megabytes of XML isn't the highest item on the priority list :)

**Comment by benalexau** [comment]
I should clarify that I'm not using Docker. My main objective is how to continue packaging versions above 953 in Arch User Repository. IB have made it incredibly difficult via their decision to:

* Distribute a self-extracting shell script that cannot be unlayered (even if you extract the embedded GZ you still need to run Install4J to emit the traditional JARS)
* Install4J has had its `-dir` option disabled (so $HOME/Jts is the mandatory output location)
* Mandatorily bundle and then require JRE 1.8.0_60 (even on machines with newer JREs, eg Arch is on 1.8.0_65 at present)
* Not versioning the installer URLs on their web site (so when you fetch the apparently stable version it's always going to be an unknown version, and even the shell script itself doesn't specify the version anywhere you can grep etc)
* Bloating the previous 53 MB ``unixmacosx_latest.jar`` into a 123 MB ``tws-latest-standalone-linux-x64.sh`` (with no way of determining the version without both downloading AND installing it!)

**Comment by benalexau** [comment]
For the benefit of people who might find this in the future and be trying to package TWS for their operating systems, https://aur.archlinux.org/cgit/aur.git/tree/?h=ib-tws now contains an updated AUR package that supports IB's new self-extracting shell script format. Of note:

* The `tws_get_version` will correctly report the version of a self-extracting shell script
* The `tws_check_update` will check for the latest version and report any new version
* The `PKGBUILD` shows how to install just the files needed, discarding the unwanted packaged JRE and all Install4J-related files (which are unnecessary in an environment with proper package installation, uninstallation and upgrade support, like the vast majority of Unix and Linux systems)

The above will fail if IB remove Install4J `-q` support. I hope they don't remove it.
