### ISSUE TITLE
How is two-factor auth handled?

### ISSUE THREAD

**Issue by jm3** [ib-controller/ib-controller#54]
How does this software behave if two-factor authentication is enabled on an IB account? I see that it handles usernames + passwords, but I don't see any mention of handling additional authentication.

**Comment by rlktradewright** [comment]
It doesn't handle two-factor authentication. This is quite deliberate.

IB provide the two-factor authentication mechanism to ensure that you really are present at the time of login. In return for this they provide certain benefits and guarantees if your account should somehow be looted.

Automating the two-factor authentication would completely annul this assurance, and would therefore disqualify you from these benefits.

So you have two options: either use IBController to automate what it can, and manually enter the additional information when requested; or opt out of the security program for TWS login (which you can do via the Account Management page on IB's website).

**Comment by jm3** [comment]
yup, i know what 2FA is and what it's for. i asked where / how in the flow would i interactively enter my credentials? you have the ability to prompt for that on the command line? do you just error if 2FA is enabled?

**Comment by rlktradewright** [comment]
You enter them in exactly the same way as when you login manually, ie TWS pops up a dialog where you enter the relevant code.

**Comment by benalexau** [comment]
For more information on two factor authentication, including workarounds, please see issue #25.
