### ISSUE TITLE
ExistingSesionDetection problems

### ISSUE THREAD

**Issue by Menox10** [ib-controller/ib-controller#56]
I have a problem with ExistingSesionDetection=secondary I used it with the idea that when I would like to login TWS main program that it stops automatic the script and when I am ready I could start every hour a crontab and connect when it is needed. This unfortunately does not work for me?? Maybe I need to set something in Windows 8.1 TWS configuration??

**Comment by Menox10** [comment]
I SOLVED this issue myself. It is important that the configuration file IBController.ini is placed in the HOME directory (IBCINI="$HOME/IBController.ini"). I placed it there but I modified a second version in $HOME/IBController/IBController.ini 

The primary version had ExistingSesionDetection=primary and causing problems with the TWS main program startup.

**Comment by rlktradewright** [comment]
What you said isn't correct.

You can put IBController.ini anywhere you like. What IS important is that the line beginning 

`IBCINI=`

in IBControllerStart.sh must contain the correct path for IBController.ini.

**Comment by Menox10** [comment]
You are right. At the moment it is working as it should work.
