### ISSUE TITLE
ReadOnlyLogin Parameter in ini FIle does not work

### ISSUE THREAD

**Issue by marknow22** [ib-controller/ib-controller#58]
Dear Developers!

I would like to use the IBController on a headless ubuntu machine and I would like to bypass the tokenlogin with the ReadOnlyLogin parameter. Unfortunately this does not work although I have set 

ReadOnlyLogin=yes 

When testiing it on my local workstation with TWS Build 952.1e, the Login procedure stops at the security token entry, and I need to click the button ReadOnly manually.

Is there something that can be done?

With regards
Markus

**Comment by marknow22** [comment]
![screenshot_023](https://cloud.githubusercontent.com/assets/8896122/12496224/a891fa8e-c094-11e5-9e4b-d1f8961894c1.png)

**Comment by rlktradewright** [comment]
There only seem to me to be three possibilities:

1. The IBController.jar file actually being used is not the one dated 2 October 2015: please check that you are using the correct version.

2. The IBController.ini file actually being used is not the one in which you set `ReadOnlyLogin=yes`: please check this.

3. For some reason the dialog is not being recognised by IBController. To check out why this is, I'll need extra diagnostics. So please set 

`LogComponents=yes` 

in your IBController.ini, run it to the same point as in your screenshot, and email me the TWS logfile at rlking(at)aultan.com. This setting will cause details of the structure of all dialogs encountered by IBController to be written to the logfile, which will enable me to determine if there is something unexpected about the dialog. Remove this setting from IBController.ini once you're done, as it can significantly increase the size of the logfile and has a small performance impact on TWS.

**Comment by rlktradewright** [comment]
Oops, I've just realised that I haven't released the version of the code that recognises the current dialog as in your screenshot. IB changed it quite some time ago, and I did a fix but I'd completely forgotten about it.

I'm currently working on a new release, but it'll be a couple more days till I put it up on GitHub.

In the meantime, please use the IBController.jar in the attached zip file to replace the one in your IBController directory. That should do the trick. Note that this zip is not the official 2.15.0 release of IBController, just an interim version, so please don't pass it to anyone else.

[IBController-2.15.0-interim.zip](https://github.com/ib-controller/ib-controller/files/100048/IBController-2.15.0-interim.zip)

So no need for the diagnostics described above, unless this one doesn't work properly.

**Comment by rlktradewright** [comment]
Please let me know if this replacement jar worked.

It's rather late here in the UK now, so if you need any further assistance it will have to wait till tomorrow!

**Comment by marknow22** [comment]
Dear Richard,

thank you very much. I will test it today. In Germany it has been also late
and I have not anticipated such a quick answer. Thanks a lot for your help.

Cheers Markus
Am 22.01.2016 01:28 schrieb "Richard L King" <notifications@github.com>:

**Comment by marknow22** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Richard,

it just perfectly works :-)

With regards
Markus

Markus Nowatzki
Web: http://www.smuek.de
Mail: smuek@smuek.de
Phone: +49 9252 357 88 86
Mobile: +49 174 179 66 70
Fax: +49 9252 357 88 87


Am 22.01.2016 um 01:28 schrieb Richard L King:
> > Please let me know if this replacement jar worked. > > It's rather
late here in the UK now, so if you need any further assistance it will
have to wait till tomorrow! > > — > Reply to this email directly or view
it on GitHub
<https://github.com/ib-controller/ib-controller/issues/58#issuecomment-173760389>.
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iEYEARECAAYFAlaidi0ACgkQVUxGkSnSBYjHLgCglDCx0q+aoxtEswYrCZf/nrh/
4hsAnRv+zAxTMEQfwFnDQRSJ/S8Y3ZMS
=Y3C6
-----END PGP SIGNATURE-----

**Comment by rlktradewright** [comment]
Glad to hear it!

Let's leave this Issue open for the moment in case anyone else hits the problem before I manage to release the new version (which is taking longer than I expected, due to grappling with scripting - a job I thoroughly detest!).

**Comment by rlktradewright** [comment]
Anyone wishing to use `ReadOnlyLogin=yes` should use IBController v3.0.0 and TWS 952 or later.
