### ISSUE TITLE
tws version 952 not installed....what silly scripting

### ISSUE THREAD

**Issue by arbitrage-technology** [ib-controller/ib-controller#71]
several years ago i was using IBcontroller old version..evrything was working smooth

then i decided to reuse again and found this version unworkable...just because the author wanted to complicaqte the life with tws dir\version\....

if it take time to put your head to repare a silly script, laucnh tws by hand every day, it will make you loose les time ...pffffff....

**Comment by rlktradewright** [comment]
Thank you for your incisive comment.

Yes, there is a problem that I failed to notice when I should have. It's called making a mistake. People do sometimes make mistakes.

The mistake will be fixed quite soon (but if you want to continue starting TWS by hand, I really don't mind at all).

Actually you can easily fix it yourself if you don't think it's too silly. Here's what to do:

1. Locate the file C:\IBController\Scripts\IBController.bat

2. Open the file in Notepad (or any other text editor)

3. Near the very end of the file, find the line that begins with:

    %JAVA_HOME%\java.exe -cp …

    and change it so that it becomes:

    "%JAVA_HOME%\java.exe" -cp …

4. Save the file.

5. Now when you run IBController it should work fine.

**Comment by arbitrage-technology** [comment]
thx;

sorry for the comment but i was completely down after 10 hours 
programming...

thx again for your contribution

David
