### ISSUE TITLE
IB-Controller Login doesn't always work

### ISSUE THREAD

**Issue by DxCx** [ib-controller/ib-controller#80]
Hi,

I'm trying to use IB-Controller, however, sometimes, when it loads, it prints like it should've pressed login, but nothing really happens:
tws_1 | ------------------------------------------------------------
tws_1 | 07:29:26:399 IBController: ini file is /opt/IBController/IBController.ini
tws_1 | 07:29:26:407 IBController: IBControllerServer is started.
tws_1 | 07:29:26:472 IBController: IBControllerServer listening on address: 0124e56ab3d8/172.17.0.2 port: 7462
tws_1 | 07:29:26:505 IBController: TWS settings directory is /opt/IBJts/jars
tws_1 | 07:29:26:578 JTS-Main: dayInit: new values: dayOfTheWeek: 3 (Tue), YYYYMMofToday: 201604, YYYYMMDDofToday: 20160419
tws_1 | 07:29:31:956 JTS-Main: getFileFromUrl: dest=/opt/IBJts/jars/locales.jar empty sourceSize=87394
tws_1 | 07:29:32:665 JTS-Main: Build 955.4m, Apr 4, 2016 10:27:08 AM
tws_1 | 07:29:33:236 IBController: detected frame entitled: Login; event=Opened
tws_1 | 07:29:33:282 IBController: detected frame entitled: Login; event=Activated
tws_1 | 07:29:33:289 IBController: Button was disabled, has been enabled: Login
tws_1 | 07:29:33:289 IBController: Click button: Login

I'm using TWS 955.4m along with IBController-v3.0.1

**Comment by rlktradewright** [comment]
Please look at the GitHub page for Release 3.0.1 of IBController.

Look at the first sentence in big bold letters. It says this:

**PLEASE DO NOT TRY TO USE THIS RELEASE OF IBCONTROLLER WITH TWS 955.4g OR LATER. IB have made some significant changes to the installed files for this version, and IBController no longer works with it. This will be corrected as soon as possible, but in the meantime use earlier versions of TWS 955 or TWS 9554, or stick with the stable version (TWS 952).**

Is there something about this statement that is unclear? Please let me know if I need to improve my English, or whether you know of some way I can persuade people to actually read things and understand them.

**Comment by djangocreation** [comment]
@rlktradewright How to download a previous version of TWS ?

**Comment by rlktradewright** [comment]
There are only two versions of TWS you should be interested in: the offline stable version, which is currently TWS 952.2, and the offline latest version which is TWS 955.4. The latter is not supported by IBController 3.0.1, but the next release of IBController will support it.

Both these offline versions are available via the download page on IB's website.

**Comment by djangocreation** [comment]
Ok, Thanks a lot. I download a correct Offline version (TWS 952.2) here : https://www.interactivebrokers.com/en/index.php?f=14099#tws-software

Unfortunately, login and password set in ~/IBController/IBController.ini doesn't load when run /opt/IBController/IBControllerStart.sh

Any ideas ?

**Comment by rlktradewright** [comment]
Tell me what happens when you run IBControllerStart.sh.

**Comment by djangocreation** [comment]
I run the script : 
user:/opt/IBController$ ./IBControllerStart.sh 
Generating the classpath
Classpath=/home/christophe/Jts/952/jars/jts4launch.jar:/home/christophe/Jts/952/jars/log4j-1.2.17.jar:/home/christophe/Jts/952/jars/total.jar:/home/christophe/Jts/952/jars/twslaunch-install4j-1.5.jar:/home/christophe/Jts/952/jars/twslaunch.jar:/opt/IBController/IBController.jar

Generating the JAVA VM options
Java VM Options= -Xmx768m

Determining the location of java.exe
/home/christophe/.i4j_jres/1.8.0_60_64/bin
Location of java.exe=/home/christophe/.i4j_jres/1.8.0_60_64/bin

~/Jts /opt/IBController
Starting IBController with this command:
/home/christophe/.i4j_jres/1.8.0_60_64/bin/java -cp /home/christophe/Jts/952/jars/jts4launch.jar:/home/christophe/Jts/952/jars/log4j-1.2.17.jar:/home/christophe/Jts/952/jars/total.jar:/home/christophe/Jts/952/jars/twslaunch-install4j-1.5.jar:/home/christophe/Jts/952/jars/twslaunch.jar:/opt/IBController/IBController.jar -Xmx768m ibcontroller.IBController /home/christophe/IBController/IBController.ini

System Properties
------------------------------------------------------------
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = /home/christophe/.i4j_jres/1.8.0_60_64/lib/amd64
java.vm.version = 25.60-b23
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = FR
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /home/christophe/Jts
java.runtime.version = 1.8.0_60-b27
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /home/christophe/.i4j_jres/1.8.0_60_64/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = UTF-8
java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 3.16.0-4-amd64
user.home = /home/christophe
user.timezone = Europe/Paris
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = UTF-8
java.specification.version = 1.8
java.class.path = /home/christophe/Jts/952/jars/jts4launch.jar:/home/christophe/Jts/952/jars/log4j-1.2.17.jar:/home/christophe/Jts/952/jars/total.jar:/home/christophe/Jts/952/jars/twslaunch-install4j-1.5.jar:/home/christophe/Jts/952/jars/twslaunch.jar:/opt/IBController/IBController.jar
user.name = christophe
java.vm.specification.version = 1.8
sun.java.command = ibcontroller.IBController /home/christophe/IBController/IBController.ini
java.home = /home/christophe/.i4j_jres/1.8.0_60_64
sun.arch.data.model = 64
user.language = fr
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.8.0_60
java.ext.dirs = /home/christophe/.i4j_jres/1.8.0_60_64/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /home/christophe/.i4j_jres/1.8.0_60_64/lib/resources.jar:/home/christophe/.i4j_jres/1.8.0_60_64/lib/rt.jar:/home/christophe/.i4j_jres/1.8.0_60_64/lib/sunrsasign.jar:/home/christophe/.i4j_jres/1.8.0_60_64/lib/jsse.jar:/home/christophe/.i4j_jres/1.8.0_60_64/lib/jce.jar:/home/christophe/.i4j_jres/1.8.0_60_64/lib/charsets.jar:/home/christophe/.i4j_jres/1.8.0_60_64/lib/jfr.jar:/home/christophe/.i4j_jres/1.8.0_60_64/classes
java.vendor = Oracle Corporation
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.cpu.isalist = 
------------------------------------------------------------
15:52:52:141 IBController: ini file is /home/christophe/IBController/IBController.ini
15:52:52:150 IBController: IBControllerServer is started.
15:52:52:225 IBController: IBControllerServer listening on address: laptop-pro-asus/127.0.1.1 port: 7462
15:52:52:274 IBController: TWS settings directory is /home/christophe/Jts
15:52:52:353 JTS-Main: dayInit: new values: dayOfTheWeek: 5 (Thu), YYYYMMofToday: 201604, YYYYMMDDofToday: 20160421
15:52:52:586 JTS-Main: LOCALE: needToUpdate  dest=/home/christophe/Jts/locales.jar  sourceMod=2016-02-23 13:38:37  destMod=2016-02-23 13:38:37  sourceSize=87394  destSize=87394  conditions=[NEWER_REMOTE, LOCAL_IN_FUTURE, SIZE_DIFFERS]  download=false
15:52:53:363 JTS-Main: Build 952.2j, Mar 21, 2016 3:48:51 PM


A screen with empty login/passwd  shows.

Thanks a lot

**Comment by rlktradewright** [comment]
Well that all looks fine. The only thing I can think of that could cause this is that you haven't set the user id and password settings correctly. Note that the setting names are case sensitive: here's an example of what it should look like (for the demo account):

IbLoginId=edemo
IbPassword=demouser
PasswordEncrypted=no

Perhaps try pasting these into your IBController.ini and see if it works. Also make sure that you don't have duplicate entries.

Also make sure that these lines in IBControllerStart.sh don't have anything after the =

TWSUSERID=
TWSPASSWORD=

If you still can't make it work, either post the contents of your IBController.ini file (with your username and password replaced by *s), or email it to me at rlking (at) aultan.com

**Comment by rlktradewright** [comment]
Since no further feedback has been received, I'll close this now.
