### ISSUE TITLE
IB-Controller API Socket is not enabled by default

### ISSUE THREAD

**Issue by DxCx** [ib-controller/ib-controller#81]
Hi,

I'm trying to use IB-Controller, however after logged in, the API socket is not started.
i need to go into configurations and tick on it to enable it:

File->Global Configurations->API->Settings->Enable ActiveX and Socket Clients

I'm using TWS 955.4m along with IBController-v3.0.1

**Comment by rlktradewright** [comment]
IBController is not a TWS configuration mechanism. You have to configure TWS and the API yourself. 

There are a great many options that you can configure, not to mention various popup messages that occur when you start placing API orders and so on which you need to see and then perhaps ask TWS not to show them again. I have absolutely no intention of making all these things settable via IBController.

Note that if you're using the demo TWS, you actually get potentially a different account each time you log in, so any settings from a previous demo session won't necessarily carry forward.
