### ISSUE TITLE
IBControllerstart.bat scheduled to auto start at auto PC login

### ISSUE THREAD

**Issue by clarkys** [ib-controller/ib-controller#86]
Hi,
IBControllerstart.bat has been working wonderfully. However, when I scheduled this .bat to run at PC auto login, TWS 954 hangs due to an Internet connectivity issue. When I move the mouse, TWS loads just fine; this happens every time. FYI, PC auto login is working fine. Can someone help?

**Comment by rlktradewright** [comment]
When I get a minute I'll try to replicate what you've done. I already have one machine that auto-logs-in, so it'll be easy enough to set it up: however that machine also runs a number of important virtual machines, so I need to do this at an appropriate time.

I have to say though that once IBController has started TWS, it's pretty much out of the picture until TWS actually does something with the user interface, so if TWS is hanging I doubt there's anything that IBController can do to help.

**Comment by clarkys** [comment]
Thank you. That's what I thought too.
