### ISSUE TITLE
IBController3.0.1 TWS 952 on Windows 8.1, java.lang.ClassNotFoundException: jclient.LoginFrame

### ISSUE THREAD

**Issue by hemantyevale** [ib-controller/ib-controller#87]
Hi,

I downloaded TWS 952 and installed on Widows 8.1. TWS and my app (uses TWS API)
works fine when I start it manually.

When I try to start TWS via IBController3.0.1, it gives runtime error -
java.lang.ClassNotFoundException: jclient.LoginFrame

After I downloaded 952 and installed, the installation didn't have 952 directory under C:\Jts.
So, I created a link C:\Jts\952 to C:\Jts.

The jars directory has log4j-1.2.17.jar, twslaunch.stable.jar and twslaunch-install4j-1.5.jar.
I ran jar -tvf | grep Login on all of them. None of them have LoginFrame class.

I have an old version of TWS 946 which has jts.jar which has LoginFrame class.

I followed UserGuide instructions carefully. Am I missing something?
How can I get IBController3.0.1 working with TWS 952 on Windows 8.1 ?
Thank you for your help!

- Hemant.

**Comment by rlktradewright** [comment]
Well, if there was no C:\Jts\952 directory then you didn't follow the instructions carefully enough!

**YOU HAVE TO USE THE OFFLINE VERSION OF TWS. IBCONTROLLER DOES NOT WORK WITH THE SELF-UPDATING VERSION.**

Sorry for being a bit loud, but I've said this over and over and over and over again!

So delete your link, uninstall the TWS you installed (you don't have to but it might save some confusion), go to this page: 

https://www.interactivebrokers.com/en/index.php?f=14099#tws-software

and follow the link labelled offline TWS. Install that and try again.

**Comment by hemantyevale** [comment]
Thank you for your quick response! I appreciate it. I missed the word "OFFLINE". I get it now.
Sorry for the trouble. I downloaded the offline version and it does have 952 directory. It also has
jts4launch.jar which has LoginFrame class. I will try IBController3.0.1. 
Thank you for your help!

**Comment by hemantyevale** [comment]
IBController3.0.1 now works for me with TWS 952 on Windows8.1!
Richard, thank you for your help!
