### ISSUE TITLE
IBController cannot connect to IB sever

### ISSUE THREAD

**Issue by clarkys** [ib-controller/ib-controller#89]
I cannot connect to IB server due to following issues. Please see attached.

![screenhunter_06 may 13 18 45](https://cloud.githubusercontent.com/assets/19170592/15263951/64cd0824-193c-11e6-8172-a4bcb8c54aaa.jpg)
![screenhunter_07 may 13 18 47](https://cloud.githubusercontent.com/assets/19170592/15263955/67ab2922-193c-11e6-9ae8-7442ccce801a.jpg)

**Comment by rlktradewright** [comment]
I don't have a clue what this is about. You'll have to provide more information about what you were trying to do.

**Comment by clarkys** [comment]
Sorry for the confusion.

Usually IBController would auto login and help stay login to IB TWS954 without any problems. Yesterday, however, IBController was unable auto login after an TWS disconnect. This same message 
kept generating for the entire trading day. I'd like to know whether this is caused by TWS or IBController. 

Thank you for taking your time to respond.

**Comment by benalexau** [comment]
@clarkys unfortunately those screen shots do not represent a full exception stack trace.

It might help to try upgrading to IBController 3.2.0-beta.1, which has just been released. This might resolve your problem, particularly as it includes reworked startup shell scripts. But if not, the new release also generates a daily log file which you could include in this ticket.

**Comment by rlktradewright** [comment]
@clarkys 

This is almost certainly just a glitch in TWS. You say 'IBController was unable auto login after an TWS disconnect', but IBController doesn't automatically login after a disconnection. In fact IBController itself never logs in: all it does is put the username and password into the relevant fields when TWS displays the login dialog. So if TWS disconnects but doesn't display the login dialog, IBController is simply not involved.
