### ISSUE TITLE
IBController 3.2.0-beta 'DisplayBannerAndLaunch.sh' fails 

### ISSUE THREAD

**Issue by nmatare** [ib-controller/ib-controller#90]
![error](https://cloud.githubusercontent.com/assets/16658157/15266652/26302070-1972-11e6-92ea-2656e12911cc.png)

I'm using the 3.2.0-beta.1 version with TWS 955.4I on a Linux box. After install and configuration, IBController keeps throwing the above exception. It appears to be having issues finding/reading/writing to a log file when using the supporting script 'DisplayBannerAndLaunch.sh'. 

I've played around with 'LOG_PATH=~/IBController/Logs' from 'IBControllerStart.sh' by reassigning the path, manually creating a log file, and even commenting-out the troublesome code. No dice. 

At best, I can bypass the exception, but TWS fails to launch and the script hangs at the terminal window.

**Comment by benalexau** [comment]
I'm speculating here, but a review of [DisplayBannerAndLaunch.sh](https://github.com/ib-controller/ib-controller/blob/master/resources/Scripts/DisplayBannerAndLaunch.sh) does not declare a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)). Can you try adding ``#!/bin/bash`` to the first line of your ``/opt/IBController/Scripts/DisplayBannerAndLaunch.sh`` and see if the message clears up? Can you also try ``export LOG_PATH=/tmp``, to ensure visibility in sub-shells?

**Comment by benalexau** [comment]
Actually can you confirm you are launching via ``IBControllerGatewayStart.sh`` or ``IBControllerStart.sh``? In the header of this file is the ``LOG_PATH`` and it gets ``export``ed later. Note this file is also missing a shebang.

**Comment by nmatare** [comment]
Success! 

`#!/bin/bash` should be included in first line of ''DisplayBannerAndLaunch.sh'; TWS loads successfully afterwards.

Thanks for your timely help! @benalexau
