### ISSUE TITLE
Regarding the Client ID

### ISSUE THREAD

**Issue by shakti-vyjayanthi** [ib-controller/ib-controller#93]
I wanted to know where can I specify the Master Client Id in the API.

**Comment by rlktradewright** [comment]
You can't set this via IBController. You must manually set it via the TWS/Gateway global configuration dialog.

IBController is not a TWS/Gateway configuration mechanism. There are far too many configuration options for IBController to manage them all. 

So you have to set up your TWS or Gateway as you want, and then IBController will automate the running of it. That's all it's for.
