### ISSUE TITLE
Regarding Authentication Permissions

### ISSUE THREAD

**Issue by shakti-vyjayanthi** [ib-controller/ib-controller#97]
While running the script, we get a second factor authentication, as shown in the screenshot attached.
![screenshot from 2016-05-24 12-04-21](https://cloud.githubusercontent.com/assets/17611599/15494698/85a6db18-21a9-11e6-8c3a-6a73032764ca.png)
 I tried changing a setting in the Ini file, "ReadOnlyLogin=yes", but this prompt still pops up. Is there anything else I can do or need to take care of?

**Comment by a8d7e8** [comment]
Duplicated, see #25 .

Next time search before asking.

**Comment by rlktradewright** [comment]
@a8d7e8 please try to understand what is being described before accusing people of duplicating posts. This isn't a duplicate.

@shakti-vyjayanthi  if you have set `ReadOnlyLogin-yes` and it's not logging in automatically, then yes, something is wrong. Can you please set 

`LogComponents=yes` 

in your .ini file, run IBController again to the point shown above, then locate the TWS log file at C:\Jts\log.Tue.txt and attach it to your reply. This will enable me to examine the structure of the login dialogs to see if something has been changed with the introduction of the new two factor phone app.

Thanks.
