### ISSUE TITLE
Allow connections only from localhost

### ISSUE THREAD

**Issue by shakti-vyjayanthi** [ib-controller/ib-controller#99]
When we start the gateway, there is a check box for "Allow connections only from localhost". Is there a way to automatically uncheck this box? I have already entered the setting for AcceptIncomingConnectionAction as accept. But does this setting allow connections if the box is checked?

**Comment by jaredbroad** [comment]
Welcome @shakti-vyjayanthi, this falls under the category of updating IB settings which is currently outside of the domain of IBController. We're looking into it though and may support it in the future.
